apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: neolesk

build:
  artifacts:
    - image: darren/neolesk
      context: .
      docker:
        dockerfile: Dockerfile
    - image: darren/mcp-relay
      context: mcp-relay
      docker:
        dockerfile: Dockerfile
  local:
    push: true

deploy:
  kubectl:
    defaultNamespace: kroki

manifests:
  kustomize:
    paths:
      - deploy
    buildArgs:
      - --enable-helm
