apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: niolesk

build:
  artifacts:
    - image: darren/niolesk
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NIOLESK_KROKI_ENGINE: https://kroki.io/
  local:
    push: true

manifests:
  kustomize:
    paths:
      - deploy
    buildArgs:
      - --enable-helm
