apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: neolesk

build:
  artifacts:
    - image: darren/neolesk
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          EXPO_PUBLIC_KROKI_ENGINE: "{{.EXPO_PUBLIC_KROKI_ENGINE}}"
  local:
    push: true

manifests:
  kustomize:
    paths:
      - deploy
    buildArgs:
      - --enable-helm
