name = "niolesk"
pages_build_output_dir = "dist"

[env.production]
routes = [
    { pattern = "interestingproblems.com/dac/*", zone_name = "interestingproblems.com" },
]

[env.production.vars]
VITE_BASE_PATH = "/dac/"
