import { defineExamples, lines } from '../define';

const diagramsnet = defineExamples([
    {
        diagramType: 'diagramsnet',
        default: true,
        description: 'Default',
        title: 'diagrams.net',
        doc: 'https://www.drawio.com/',
        language: 'xml',
        keywords: ['drawio', 'diagram', 'flowchart', 'network', 'uml'],
        source: lines([
            '<mxfile>',
            '  <diagram name="Page-1" id="page1">',
            '    <mxGraphModel dx="1422" dy="762" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="850" pageHeight="1100">',
            '      <root>',
            '        <mxCell id="0"/>',
            '        <mxCell id="1" parent="0"/>',
            '        <mxCell id="2" value="Client" style="rounded=1;whiteSpace=wrap;fillColor=#dae8fc;strokeColor=#6c8ebf;" vertex="1" parent="1">',
            '          <mxGeometry x="200" y="80" width="120" height="60" as="geometry"/>',
            '        </mxCell>',
            '        <mxCell id="3" value="API Gateway" style="rounded=1;whiteSpace=wrap;fillColor=#d5e8d4;strokeColor=#82b366;" vertex="1" parent="1">',
            '          <mxGeometry x="200" y="200" width="120" height="60" as="geometry"/>',
            '        </mxCell>',
            '        <mxCell id="4" value="Service A" style="rounded=1;whiteSpace=wrap;fillColor=#fff2cc;strokeColor=#d6b656;" vertex="1" parent="1">',
            '          <mxGeometry x="80" y="320" width="120" height="60" as="geometry"/>',
            '        </mxCell>',
            '        <mxCell id="5" value="Service B" style="rounded=1;whiteSpace=wrap;fillColor=#fff2cc;strokeColor=#d6b656;" vertex="1" parent="1">',
            '          <mxGeometry x="320" y="320" width="120" height="60" as="geometry"/>',
            '        </mxCell>',
            '        <mxCell id="6" value="Database" style="shape=cylinder3;whiteSpace=wrap;boundedLbl=1;backgroundOutline=1;size=15;fillColor=#f8cecc;strokeColor=#b85450;" vertex="1" parent="1">',
            '          <mxGeometry x="200" y="440" width="120" height="80" as="geometry"/>',
            '        </mxCell>',
            '        <mxCell id="7" style="edgeStyle=orthogonalEdgeStyle;" edge="1" source="2" target="3" parent="1">',
            '          <mxGeometry relative="1" as="geometry"/>',
            '        </mxCell>',
            '        <mxCell id="8" style="edgeStyle=orthogonalEdgeStyle;" edge="1" source="3" target="4" parent="1">',
            '          <mxGeometry relative="1" as="geometry"/>',
            '        </mxCell>',
            '        <mxCell id="9" style="edgeStyle=orthogonalEdgeStyle;" edge="1" source="3" target="5" parent="1">',
            '          <mxGeometry relative="1" as="geometry"/>',
            '        </mxCell>',
            '        <mxCell id="10" style="edgeStyle=orthogonalEdgeStyle;" edge="1" source="4" target="6" parent="1">',
            '          <mxGeometry relative="1" as="geometry"/>',
            '        </mxCell>',
            '        <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;" edge="1" source="5" target="6" parent="1">',
            '          <mxGeometry relative="1" as="geometry"/>',
            '        </mxCell>',
            '      </root>',
            '    </mxGraphModel>',
            '  </diagram>',
            '</mxfile>',
        ]),
    },
]);

export default diagramsnet;
