import { defineExamples, lines } from '../define';

const nomnoml = defineExamples([
    {
        diagramType: "nomnoml",
        default: true,
        description: "Default",
        title: "Nomnoml",
        doc: "https://nomnoml.com/",
        keywords: ["UML", "diagram", "state", "activity", "class", "object", "entity", "relation", "ERD", "use cases", "deployment", "component"],
        source: lines([
            "[Pirate|eyeCount: Int|raid();pillage()|",
            "  [beard]--[parrot]",
            "  [beard]-:>[foul mouth]",
            "]",
            "",
            "[<table>mischief | bawl | sing || yell | drink]",
            "",
            "[<abstract>Marauder]<:--[Pirate]",
            "[Pirate]- 0..7[mischief]",
            "[jollyness]->[Pirate]",
            "[jollyness]->[rum]",
            "[jollyness]->[singing]",
            "[Pirate]-> *[rum|tastiness: Int|swig()]",
            "[Pirate]->[singing]",
            "[singing]<->[rum]",
            "",
            "[<start>st]->[<state>plunder]",
            "[plunder]->[<choice>more loot]",
            "[more loot]->[st]",
            "[more loot] no ->[<end>e]",
            "",
            "[<actor>Sailor] - [<usecase>shiver me;timbers]",
        ]),
    },
    {
        diagramType: "nomnoml",
        default: false,
        description: "Object diagram",
        title: "Nomnoml",
        doc: "https://nomnoml.com/",
        keywords: ["UML", "diagram", "activity", "class", "object", "entity", "relation", "ERD", "deployment", "component"],
        source: lines([
            "[Pirate|eyeCount: Int|raid();pillage()|",
            "  [beard]--[parrot]",
            "  [beard]-:>[foul mouth]",
            "]",
            "",
            "[<abstract>Marauder]<:--[Pirate]",
            "[Pirate]- 0..7[mischief]",
            "[jollyness]->[Pirate]",
            "[jollyness]->[rum]",
            "[jollyness]->[singing]",
            "[Pirate]-> *[rum|tastiness: Int|swig()]",
            "[Pirate]->[singing]",
            "[singing]<->[rum]",
        ]),
    },
    {
        diagramType: "nomnoml",
        default: false,
        description: "State/Activity diagram",
        title: "Nomnoml",
        doc: "https://nomnoml.com/",
        keywords: ["UML", "diagram", "state", "activity"],
        source: lines([
            "[<start>st]->[<state>plunder]",
            "[plunder]->[<choice>more loot]",
            "[more loot]->[st]",
            "[more loot] no ->[<end>e]",
        ]),
    },
    {
        diagramType: "nomnoml",
        default: false,
        description: "Use case diagram",
        title: "Nomnoml",
        doc: "https://nomnoml.com/",
        keywords: ["UML", "diagram", "use cases"],
        source: lines([
            "[<actor>Sailor] - [<usecase>shiver me;timbers]",
        ]),
    },
]);

export default nomnoml;
