import { defineExamples, lines } from '../define';

const pikchr = defineExamples([
    {
        diagramType: "pikchr",
        default: true,
        description: "Default",
        title: "Pikchr",
        doc: "https://pikchr.org/home/doc/trunk/doc/examples.md",
        keywords: ["markup", "diagram", "technical", "documentation"],
        source: lines([
            "$r = 0.2in",
            "linerad = 0.75*$r",
            "linewid = 0.25",
            "",
            "# Start and end blocks",
            "#",
            "box \"element\" bold fit",
            "line down 50% from last box.sw",
            "dot rad 250% color black",
            "X0: last.e + (0.3,0)",
            "arrow from last dot to X0",
            "move right 3.9in",
            "box wid 5% ht 25% fill black",
            "X9: last.w - (0.3,0)",
            "arrow from X9 to last box.w",
            "",
            "",
            "# The main rule that goes straight through from start to finish",
            "#",
            "box \"object-definition\" italic fit at 11/16 way between X0 and X9",
            "arrow to X9",
            "arrow from X0 to last box.w",
            "",
            "# The LABEL: rule",
            "#",
            "arrow right $r from X0 then down 1.25*$r then right $r",
            "oval \" LABEL \" fit",
            "arrow 50%",
            "oval \"\\\":\\\"\" fit",
            "arrow 200%",
            "box \"position\" italic fit",
            "arrow",
            "line right until even with X9 - ($r,0) \\",
            "  then up until even with X9 then to X9",
            "arrow from last oval.e right $r*0.5 then up $r*0.8 right $r*0.8",
            "line up $r*0.45 right $r*0.45 then right",
            "",
            "# The VARIABLE = rule",
            "#",
            "arrow right $r from X0 then down 2.5*$r then right $r",
            "oval \" VARIABLE \" fit",
            "arrow 70%",
            "box \"assignment-operator\" italic fit",
            "arrow 70%",
            "box \"expr\" italic fit",
            "line right until even with X9 - ($r,0) \\",
            "  then up until even with X9 then to X9",
            "",
            "# The PRINT rule",
            "#",
            "arrow right $r from X0 then down 3.75*$r then right $r",
            "oval \"\\\"print\\\"\" fit",
            "arrow",
            "box \"print-args\" italic fit",
            "line right until even with X9 - ($r,0) \\",
            "  then up until even with X9 then to X9",
        ]),
    },
    {
        diagramType: "pikchr",
        default: false,
        description: "",
        title: "Pikchr",
        doc: "https://pikchr.org/home/doc/trunk/doc/examples.md",
        keywords: ["markup", "diagram", "technical", "documentation"],
        source: lines([
            "arrow right 200% \"Markdown\" \"Source\"",
            "box rad 10px \"Markdown\" \"Formatter\" \"(markdown.c)\" fit",
            "arrow right 200% \"HTML+SVG\" \"Output\"",
            "arrow <-> down 70% from last box.s",
            "box same \"Pikchr\" \"Formatter\" \"(pikchr.c)\" fit",
            "",
        ], true),
    },
    {
        diagramType: "pikchr",
        default: false,
        description: "",
        title: "Pikchr",
        doc: "https://pikchr.org/home/doc/trunk/doc/examples.md",
        keywords: ["markup", "diagram", "technical", "documentation"],
        source: lines([
            "    lineht *= 0.4",
            "    $margin = lineht*2.5",
            "    scale = 0.75",
            "    fontscale = 1.1",
            "    charht *= 1.15",
            "    down",
            "In: box \"Interface\" wid 150% ht 75% fill white",
            "    arrow",
            "CP: box same \"SQL Command\" \"Processor\"",
            "    arrow",
            "VM: box same \"Virtual Machine\"",
            "    arrow down 1.25*$margin",
            "BT: box same \"B-Tree\"",
            "    arrow",
            "    box same \"Pager\"",
            "    arrow",
            "OS: box same \"OS Interface\"",
            "    box same with .w at 1.25*$margin east of 1st box.e \"Tokenizer\"",
            "    arrow",
            "    box same \"Parser\"",
            "    arrow",
            "CG: box same ht 200% \"Code\" \"Generator\"",
            "UT: box same as 1st box at (Tokenizer,Pager) \"Utilities\"",
            "    move lineht",
            "TC: box same \"Test Code\"",
            "    arrow from CP to 1/4<Tokenizer.sw,Tokenizer.nw> chop",
            "    arrow from 1/3<CG.nw,CG.sw> to CP chop",
            "",
            "    box ht (In.n.y-VM.s.y)+$margin wid In.wid+$margin \\",
            "       at CP fill 0xd8ecd0 behind In",
            "    line invis from 0.25*$margin east of last.sw up last.ht \\",
            "        \"Core\" italic aligned",
            "",
            "    box ht (BT.n.y-OS.s.y)+$margin wid In.wid+$margin \\",
            "       at Pager fill 0xd0ece8 behind In",
            "    line invis from 0.25*$margin east of last.sw up last.ht \\",
            "       \"Backend\" italic aligned",
            "",
            "    box ht (Tokenizer.n.y-CG.s.y)+$margin wid In.wid+$margin \\",
            "       at 1/2<Tokenizer.n,CG.s> fill 0xe8d8d0 behind In",
            "    line invis from 0.25*$margin west of last.se up last.ht \\",
            "       \"SQL Compiler\" italic aligned",
            "",
            "    box ht (UT.n.y-TC.s.y)+$margin wid In.wid+$margin \\",
            "       at 1/2<UT,TC> fill 0xe0ecc8 behind In",
            "    line invis from 0.25*$margin west of last.se up last.ht \\",
            "      \"Accessories\" italic aligned",
        ]),
    },
]);

export default pikchr;
