apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: niolesk
  namespace: kroki
  annotations:
    tailscale.com/hostname: niolesk
spec:
  defaultBackend:
    service:
      name: niolesk
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - niolesk
