import { defineExamples, lines } from '../define';

const c4plantuml = defineExamples([
    {
        diagramType: "c4plantuml",
        default: true,
        description: "Default",
        title: "C4 with PlantUML",
        doc: "https://github.com/plantuml-stdlib/C4-PlantUML",
        keywords: ["UML", "C4", "plantUML", "software architecture"],
        source: lines([
            "@startuml",
            "!include C4_Context.puml",
            "",
            "title System Context diagram for Internet Banking System",
            "",
            "Person(customer, \"Banking Customer\", \"A customer of the bank, with personal bank accounts.\")",
            "System(banking_system, \"Internet Banking System\", \"Allows customers to check their accounts.\")",
            "",
            "System_Ext(mail_system, \"E-mail system\", \"The internal Microsoft Exchange e-mail system.\")",
            "System_Ext(mainframe, \"Mainframe Banking System\", \"Stores all of the core banking information.\")",
            "",
            "Rel(customer, banking_system, \"Uses\")",
            "Rel_Back(customer, mail_system, \"Sends e-mails to\")",
            "Rel_Neighbor(banking_system, mail_system, \"Sends e-mails\", \"SMTP\")",
            "Rel(banking_system, mainframe, \"Uses\")",
            "@enduml",
        ]),
    },
    {
        diagramType: "c4plantuml",
        default: false,
        description: "Use tags",
        title: "C4 with PlantUML",
        doc: "https://github.com/plantuml-stdlib/C4-PlantUML",
        keywords: ["UML", "C4", "plantUML", "software architecture"],
        source: lines([
            "@startuml",
            "!include C4_Container.puml",
            "",
            "AddElementTag(\"v1.0\", $borderColor=\"#d73027\")",
            "AddElementTag(\"v1.1\", $fontColor=\"#d73027\")",
            "AddElementTag(\"backup\", $fontColor=\"orange\")",
            "",
            "AddRelTag(\"backup\", $textColor=\"orange\", $lineColor=\"orange\", $lineStyle = DashedLine())",
            "",
            "Person(user, \"Customer\", \"People that need products\")",
            "Person(admin, \"Administrator\", \"People that administrates the products via the new v1.1 components\", $tags=\"v1.1\")",
            "Container(spa, \"SPA\", \"angular\", \"The main interface that the customer interacts with via v1.0\", $tags=\"v1.0\")",
            "Container(spaAdmin, \"Admin SPA\", \"angular\", \"The administrator interface that the customer interacts with via new v1.1\", $tags=\"v1.1\")",
            "Container(api, \"API\", \"java\", \"Handles all business logic (incl. new v1.1 extensions)\", $tags=\"v1.0+v1.1\")",
            "ContainerDb(db, \"Database\", \"Microsoft SQL\", \"Holds product, order and invoice information\")",
            "Container(archive, \"Archive\", \"Audit logging\", \"Stores 5 years\", $tags=\"backup\")",
            "",
            "Rel(user, spa, \"Uses\", \"https\")",
            "Rel(spa, api, \"Uses\", \"https\")",
            "Rel_R(api, db, \"Reads/Writes\")",
            "Rel(admin, spaAdmin, \"Uses\", \"https\")",
            "Rel(spaAdmin, api, \"Uses\", \"https\")",
            "Rel_L(api, archive, \"Writes\", \"messages\", $tags=\"backup\")",
            "",
            "SHOW_LEGEND()",
            "@enduml",
        ]),
    },
]);

export default c4plantuml;
