import { defineExamples, lines } from '../define';

const d2 = defineExamples([
    {
        diagramType: "d2",
        default: true,
        description: "Default",
        title: "D2",
        doc: "https://d2lang.com/tour/connections",
        keywords: ["diagram"],
        source: lines([
            "D2 Parser: {",
            "  shape: class",
            "",
            "  # Default visibility is + so no need to specify.",
            "  +reader: io.RuneReader",
            "  readerPos: d2ast.Position",
            "",
            "  # Private field.",
            "  -lookahead: \"[]rune\"",
            "",
            "  # Protected field.",
            "  # We have to escape the # to prevent the line from being parsed as a comment.",
            "  \\#lookaheadPos: d2ast.Position",
            "",
            "  +peek(): (r rune, eof bool)",
            "  rewind()",
            "  commit()",
            "",
            "  \\#peekn(n int): (s string, eof bool)",
            "}",
            "",
            "\"github.com/terrastruct/d2.git\" -> D2 Parser",
        ]),
    },
    {
        diagramType: "d2",
        default: false,
        description: "Chess",
        title: "D2",
        doc: "https://d2lang.com/tour/connections",
        keywords: ["diagram"],
        source: lines([
            "# Actors",
            "hans: Hans Niemann",
            "",
            "defendants: {",
            "  mc: Magnus Carlsen",
            "  playmagnus: Play Magnus Group",
            "  chesscom: Chess.com",
            "  naka: Hikaru Nakamura",
            "",
            "  mc -> playmagnus: Owns majority",
            "  playmagnus <-> chesscom: Merger talks",
            "  chesscom -> naka: Sponsoring",
            "}",
            "",
            "# Accusations",
            "hans -> defendants: 'sueing for $100M'",
            "",
            "# Offense",
            "defendants.naka -> hans: Accused of cheating on his stream",
            "defendants.mc -> hans: Lost then withdrew with accusations",
            "defendants.chesscom -> hans: 72 page report of cheating",
            "",
        ], true),
    },
    {
        diagramType: "d2",
        default: false,
        description: "Twitter",
        title: "D2",
        doc: "https://d2lang.com/tour/connections",
        keywords: ["diagram"],
        source: lines([
            "timeline mixer: \"\" {",
            "  explanation: |md",
            "    ## **Timeline mixer**",
            "    - Inject ads, who-to-follow, onboarding",
            "    - Conversation module",
            "    - Cursoring,pagination",
            "    - Tweat deduplication",
            "    - Served data logging",
            "  |",
            "}",
            "People discovery: \"People discovery \\nservice\"",
            "admixer: Ad mixer {",
            "  style.fill: \"#c1a2f3\"",
            "}",
            "",
            "onboarding service: \"Onboarding \\nservice\"",
            "timeline mixer -> People discovery",
            "timeline mixer -> onboarding service",
            "timeline mixer -> admixer",
            "container0: \"\" {",
            "  graphql",
            "  comment",
            "  tlsapi",
            "}",
            "container0.graphql: GraphQL\\nFederated Strato Column",
            "container0.comment: |md",
            "  ## Tweet/user content hydration, visibility filtering",
            "|",
            "container0.tlsapi: TLS-API (being deprecated)",
            "container0.graphql -> timeline mixer",
            "timeline mixer <- container0.tlsapi",
            "twitter fe: \"Twitter Frontend\"",
            "twitter fe -> container0.graphql: iPhone web",
            "twitter fe -> container0.tlsapi: HTTP Android",
            "web: Web",
            "",
            "Iphone: iPhone",
            "Android: Android",
            "",
            "web -> twitter fe",
            "timeline scorer: \"Timeline\\nScorer\" {",
            "  style.fill: \"#ffdef1\"",
            "}",
            "home ranker: Home Ranker",
            "",
            "timeline service: Timeline Service",
            "timeline mixer -> timeline scorer: Thrift RPC",
            "timeline mixer -> home ranker: {",
            "  style.stroke-dash: 4",
            "  style.stroke: \"#000E3D\"",
            "}",
            "timeline mixer -> timeline service",
            "home mixer: Home mixer {",
            "  # style.fill: \"#c1a2f3\"",
            "}",
            "container0.graphql -> home mixer: {",
            "  style.stroke-dash: 4",
            "  style.stroke: \"#000E3D\"",
            "}",
            "home mixer -> timeline scorer",
            "home mixer -> home ranker: {",
            "  style.stroke-dash: 4",
            "  style.stroke: \"#000E3D\"",
            "}",
            "home mixer -> timeline service",
            "manhattan 2: Manhattan",
            "gizmoduck: Gizmoduck",
            "socialgraph: Social graph",
            "tweetypie: Tweety Pie",
            "home mixer -> manhattan 2",
            "home mixer -> gizmoduck",
            "home mixer -> socialgraph",
            "home mixer -> tweetypie",
            "Iphone -> twitter fe",
            "Android -> twitter fe",
            "prediction service2: Prediction Service {",
            "  style.fill: \"#F7F8FE\"",
            "}",
            "home scorer: Home Scorer {",
            "  style.fill: \"#ffdef1\"",
            "}",
            "manhattan: Manhattan",
            "memcache: Memcache",
            "",
            "fetch: Fetch {",
            "  style.multiple: true",
            "  shape: step",
            "}",
            "",
            "feature: Feature {",
            "  style.multiple: true",
            "  shape: step",
            "}",
            "scoring: Scoring {",
            "  style.multiple: true",
            "  shape: step",
            "}",
            "fetch -> feature",
            "feature -> scoring",
            "",
            "prediction service: Prediction Service {",
            "  style.fill: \"#F7F8FE\"",
            "}",
            "scoring -> prediction service",
            "fetch -> container2.crmixer",
            "",
            "home scorer -> manhattan: \"\"",
            "",
            "home scorer -> memcache: \"\"",
            "home scorer -> prediction service2",
            "home ranker -> home scorer",
            "home ranker -> container2.crmixer: Candidate Fetch",
            "container2: \"\" {",
            "  style.stroke: \"#000E3D\"",
            "  style.fill: \"#ffffff\"",
            "  crmixer: CrMixer {",
            "    style.fill: \"#F7F8FE\"",
            "  }",
            "  earlybird: EarlyBird",
            "  utag: Utag",
            "  space: Space",
            "  communities: Communities",
            "}",
            "etc: ...etc",
            "",
            "home scorer -> etc: Feature Hydration",
            "",
            "feature -> manhattan",
            "feature -> memcache",
            "feature -> etc: Candidate sources",
        ]),
    },
    {
        diagramType: "d2",
        default: false,
        description: "SQL",
        title: "D2",
        doc: "https://d2lang.com/tour/sql-tables",
        keywords: ["diagram", "SQL", "entity", "relation"],
        source: lines([
            "costumes: {",
            "  shape: sql_table",
            "  id: int {constraint: primary_key}",
            "  silliness: int",
            "  monster: int",
            "  last_updated: timestamp",
            "}",
            "",
            "monsters: {",
            "  shape: sql_table",
            "  id: int {constraint: primary_key}",
            "  movie: string",
            "  weight: int",
            "  last_updated: timestamp",
            "}",
            "",
            "costumes.monster -> monsters.id",
        ]),
    },
    {
        diagramType: "d2",
        default: false,
        description: "Markdown",
        title: "D2",
        doc: "https://d2lang.com/tour/text",
        keywords: ["diagram", "Markdown"],
        source: lines([
            "explanation: |md",
            "  # I can do headers",
            "",
            "  - lists",
            "  - lists",
            "",
            "  And other normal markdown stuff",
            "|",
            "",
        ], true),
    },
    {
        diagramType: "d2",
        default: false,
        description: "Shapes",
        title: "D2",
        doc: "https://d2lang.com/tour/shapes",
        keywords: ["diagram", "Shapes"],
        source: lines([
            "donut: {shape: circle}",
            "database.shape: cylinder",
            "you: {",
            "  shape: person",
            "}",
            "",
        ], true),
    },
    {
        diagramType: "d2",
        default: false,
        description: "Classes",
        title: "D2",
        doc: "https://d2lang.com/tour/classes",
        keywords: ["diagram", "Classes", "UML"],
        source: lines([
            "MyClass: {",
            "  shape: class",
            "",
            "  field: \"[]string\"",
            "  method(a uint64): (x, y int)",
            "}",
        ]),
    },
    {
        diagramType: "d2",
        default: false,
        description: "Code",
        title: "D2",
        doc: "https://d2lang.com/tour/text",
        keywords: ["diagram", "code"],
        source: lines([
            "explanation: |go",
            "  awsSession := From(c.Request.Context())",
            "  client := s3.New(awsSession)",
            "",
            "  ctx, cancelFn := context.WithTimeout(c.Request.Context(), AWS_TIMEOUT)",
            "  defer cancelFn()",
            "|",
        ]),
    },
]);

export default d2;
