import { defineExamples, lines } from '../define';

const ditaa = defineExamples([
    {
        diagramType: "ditaa",
        default: true,
        description: "Default",
        title: "Ditaa",
        doc: "http://ditaa.sourceforge.net/#usage",
        keywords: ["block", "asciiart", "drawing"],
        source: lines([
            "      +--------+",
            "      |        |",
            "      |  User  |",
            "      |        |",
            "      +--------+",
            "          ^",
            "  request |",
            "          v",
            "  +-------------+",
            "  |             |",
            "  |    Kroki    |",
            "  |             |---+",
            "  +-------------+   |",
            "       ^  ^         | inflate",
            "       |  |         |",
            "       v  +---------+",
            "  +-------------+",
            "  |             |",
            "  |    Ditaa    |",
            "  |             |----+",
            "  +-------------+    |",
            "             ^       | process",
            "             |       |",
            "             +-------+",
            "",
        ], true),
    },
    {
        diagramType: "ditaa",
        default: false,
        description: "Using colors",
        title: "Ditaa",
        doc: "http://ditaa.sourceforge.net/#usage",
        keywords: ["block", "asciiart", "color", "drawing"],
        source: lines([
            "Color codes",
            "/-------------+-------------\\",
            "|cRED RED     |cBLU BLU     |",
            "+-------------+-------------+",
            "|cGRE GRE     |cPNK PNK     |",
            "+-------------+-------------+",
            "|cBLK BLK     |cYEL YEL     |",
            "\\-------------+-------------/",
            "",
            "/----\\ /----\\",
            "|c33F| |cC02|",
            "|    | |    |",
            "\\----/ \\----/",
            "",
            "/----\\ /----\\",
            "|c1FF| |c1AB|",
            "|    | |    |",
            "\\----/ \\----/",
        ]),
    },
    {
        diagramType: "ditaa",
        default: false,
        description: "Using shapes, dash, and text",
        title: "Ditaa",
        doc: "http://ditaa.sourceforge.net/#usage",
        keywords: ["block", "asciiart", "drawing"],
        source: lines([
            "+-----+  +-----+  +-----+",
            "|{d}  |  |{s}  |  |{io} |",
            "|     |  |     |  |     |",
            "|     |  |     |  |     |",
            "+-----+  +-----+  +-----+",
            "",
            "-----+  /-----\\  +------+",
            "     :  |     |  :      |",
            "     |  |     |  |      |",
            "     |  |     |  |{s}   |",
            "     v  \\-=---+  +------+",
            "",
            "*----*",
            "|    |      /--*",
            "*    *      |",
            "|    |  -*--+",
            "*----*",
            "",
            "/-----------------\\",
            "| Things to do    |",
            "| cGRE            |",
            "| o Cut the grass |",
            "| o Buy jam       |",
            "| o Fix car       |",
            "| o Make website  |",
            "\\-----------------/",
        ]),
    },
]);

export default ditaa;
