import { defineExamples, lines } from '../define';

const graphviz = defineExamples([
    {
        diagramType: "graphviz",
        default: true,
        description: "Default",
        title: "GraphViz",
        doc: "https://graphviz.org/gallery/",
        keywords: ["dot", "digraph", "directed", "node"],
        source: lines([
            "digraph D {",
            "  subgraph cluster_p {",
            "    label = \"Kroki\";",
            "    subgraph cluster_c1 {",
            "      label = \"Server\";",
            "      Filebeat;",
            "      subgraph cluster_gc_1 {",
            "        label = \"Docker/Server\";",
            "        Java;",
            "      }",
            "      subgraph cluster_gc_2 {",
            "        label = \"Docker/Mermaid\";",
            "        \"Node.js\";",
            "        \"Puppeteer\";",
            "        \"Chrome\";",
            "      }",
            "    }",
            "    subgraph cluster_c2 {",
            "      label = \"CLI\";",
            "      Golang;",
            "    }",
            "  }",
            "}",
        ]),
    },
    {
        diagramType: "graphviz",
        default: false,
        description: "Data structure",
        title: "GraphViz",
        doc: "https://graphviz.org/gallery/",
        keywords: ["dot", "digraph", "directed", "node", "memory", "tree"],
        source: lines([
            "digraph g {",
            "graph [",
            "rankdir = \"LR\"",
            "];",
            "node [",
            "fontsize = \"16\"",
            "shape = \"ellipse\"",
            "];",
            "edge [",
            "];",
            "\"node0\" [",
            "label = \"<f0> 0x10ba8| <f1>\"",
            "shape = \"record\"",
            "];",
            "\"node1\" [",
            "label = \"<f0> 0xf7fc4380| <f1> | <f2> |-1\"",
            "shape = \"record\"",
            "];",
            "\"node2\" [",
            "label = \"<f0> 0xf7fc44b8| | |2\"",
            "shape = \"record\"",
            "];",
            "\"node3\" [",
            "label = \"<f0> 3.43322790286038071e-06|44.79998779296875|0\"",
            "shape = \"record\"",
            "];",
            "\"node4\" [",
            "label = \"<f0> 0xf7fc4380| <f1> | <f2> |2\"",
            "shape = \"record\"",
            "];",
            "\"node5\" [",
            "label = \"<f0> (nil)| | |-1\"",
            "shape = \"record\"",
            "];",
            "\"node6\" [",
            "label = \"<f0> 0xf7fc4380| <f1> | <f2> |1\"",
            "shape = \"record\"",
            "];",
            "\"node7\" [",
            "label = \"<f0> 0xf7fc4380| <f1> | <f2> |2\"",
            "shape = \"record\"",
            "];",
            "\"node8\" [",
            "label = \"<f0> (nil)| | |-1\"",
            "shape = \"record\"",
            "];",
            "\"node9\" [",
            "label = \"<f0> (nil)| | |-1\"",
            "shape = \"record\"",
            "];",
            "\"node10\" [",
            "label = \"<f0> (nil)| <f1> | <f2> |-1\"",
            "shape = \"record\"",
            "];",
            "\"node11\" [",
            "label = \"<f0> (nil)| <f1> | <f2> |-1\"",
            "shape = \"record\"",
            "];",
            "\"node12\" [",
            "label = \"<f0> 0xf7fc43e0| | |1\"",
            "shape = \"record\"",
            "];",
            "\"node0\":f0 -> \"node1\":f0 [",
            "id = 0",
            "];",
            "\"node0\":f1 -> \"node2\":f0 [",
            "id = 1",
            "];",
            "\"node1\":f0 -> \"node3\":f0 [",
            "id = 2",
            "];",
            "\"node1\":f1 -> \"node4\":f0 [",
            "id = 3",
            "];",
            "\"node1\":f2 -> \"node5\":f0 [",
            "id = 4",
            "];",
            "\"node4\":f0 -> \"node3\":f0 [",
            "id = 5",
            "];",
            "\"node4\":f1 -> \"node6\":f0 [",
            "id = 6",
            "];",
            "\"node4\":f2 -> \"node10\":f0 [",
            "id = 7",
            "];",
            "\"node6\":f0 -> \"node3\":f0 [",
            "id = 8",
            "];",
            "\"node6\":f1 -> \"node7\":f0 [",
            "id = 9",
            "];",
            "\"node6\":f2 -> \"node9\":f0 [",
            "id = 10",
            "];",
            "\"node7\":f0 -> \"node3\":f0 [",
            "id = 11",
            "];",
            "\"node7\":f1 -> \"node1\":f0 [",
            "id = 12",
            "];",
            "\"node7\":f2 -> \"node8\":f0 [",
            "id = 13",
            "];",
            "\"node10\":f1 -> \"node11\":f0 [",
            "id = 14",
            "];",
            "\"node10\":f2 -> \"node12\":f0 [",
            "id = 15",
            "];",
            "\"node11\":f2 -> \"node1\":f0 [",
            "id = 16",
            "];",
            "}",
        ]),
    },
    {
        diagramType: "graphviz",
        default: false,
        description: "Finite Automaton",
        title: "GraphViz",
        doc: "https://graphviz.org/gallery/",
        keywords: ["dot", "digraph", "directed", "node"],
        source: lines([
            "digraph finite_state_machine {",
            "\trankdir=LR;",
            "\tsize=\"8,5\"",
            "\tnode [shape = doublecircle]; 0 3 4 8;",
            "\tnode [shape = circle];",
            "\t0 -> 2 [label = \"SS(B)\"];",
            "\t0 -> 1 [label = \"SS(S)\"];",
            "\t1 -> 3 [label = \"S($end)\"];",
            "\t2 -> 6 [label = \"SS(b)\"];",
            "\t2 -> 5 [label = \"SS(a)\"];",
            "\t2 -> 4 [label = \"S(A)\"];",
            "\t5 -> 7 [label = \"S(b)\"];",
            "\t5 -> 5 [label = \"S(a)\"];",
            "\t6 -> 6 [label = \"S(b)\"];",
            "\t6 -> 5 [label = \"S(a)\"];",
            "\t7 -> 8 [label = \"S(b)\"];",
            "\t7 -> 5 [label = \"S(a)\"];",
            "\t8 -> 6 [label = \"S(b)\"];",
            "\t8 -> 5 [label = \"S(a)\"];",
            "}",
        ]),
    },
    {
        diagramType: "graphviz",
        default: false,
        description: "Go package import",
        title: "GraphViz",
        doc: "https://graphviz.org/gallery/",
        keywords: ["dot", "digraph", "directed", "node", "deps", "dependency", "libs", "libraries", "library", "package"],
        source: lines([
            "digraph regexp { ",
            " n0 [label=\"regexp\", URL=\"https://godoc.org/regexp\", tooltip=\"Package regexp implements regular expression search.\"];",
            " n1 [label=\"bytes\", URL=\"https://godoc.org/bytes\", tooltip=\"Package bytes implements functions for the manipulation of byte slices.\"];",
            " n2 [label=\"io\", URL=\"https://godoc.org/io\", tooltip=\"Package io provides basic interfaces to I/O primitives.\"];",
            " n3 [label=\"regexp/syntax\", URL=\"https://godoc.org/regexp/syntax\", tooltip=\"Package syntax parses regular expressions into parse trees and compiles parse trees into programs.\"];",
            " n4 [label=\"sort\", URL=\"https://godoc.org/sort\", tooltip=\"Package sort provides primitives for sorting slices and user-defined collections.\"];",
            " n5 [label=\"strconv\", URL=\"https://godoc.org/strconv\", tooltip=\"Package strconv implements conversions to and from string representations of basic data types.\"];",
            " n6 [label=\"strings\", URL=\"https://godoc.org/strings\", tooltip=\"Package strings implements simple functions to manipulate UTF-8 encoded strings.\"];",
            " n7 [label=\"sync\", URL=\"https://godoc.org/sync\", tooltip=\"Package sync provides basic synchronization primitives such as mutual exclusion locks.\"];",
            " n8 [label=\"unicode\", URL=\"https://godoc.org/unicode\", tooltip=\"Package unicode provides data and functions to test some properties of Unicode code points.\"];",
            " n9 [label=\"unicode/utf8\", URL=\"https://godoc.org/unicode/utf8\", tooltip=\"Package utf8 implements functions and constants to support text encoded in UTF-8.\"];",
            " n10 [label=\"internal/bytealg\", URL=\"https://godoc.org/internal/bytealg\", tooltip=\"\"];",
            " n11 [label=\"errors\", URL=\"https://godoc.org/errors\", tooltip=\"Package errors implements functions to manipulate errors.\"];",
            " n12 [label=\"internal/reflectlite\", URL=\"https://godoc.org/internal/reflectlite\", tooltip=\"Package reflectlite implements lightweight version of reflect, not using any package except for \\\"runtime\\\" and \\\"unsafe\\\".\"];",
            " n13 [label=\"math\", URL=\"https://godoc.org/math\", tooltip=\"Package math provides basic constants and mathematical functions.\"];",
            " n14 [label=\"math/bits\", URL=\"https://godoc.org/math/bits\", tooltip=\"Package bits implements bit counting and manipulation functions for the predeclared unsigned integer types.\"];",
            " n15 [label=\"unsafe\", URL=\"https://godoc.org/unsafe\", tooltip=\"Package unsafe contains operations that step around the type safety of Go programs.\"];",
            " n16 [label=\"internal/race\", URL=\"https://godoc.org/internal/race\", tooltip=\"Package race contains helper functions for manually instrumenting code for the race detector.\"];",
            " n17 [label=\"runtime\", URL=\"https://godoc.org/runtime\", tooltip=\"\"];",
            " n18 [label=\"sync/atomic\", URL=\"https://godoc.org/sync/atomic\", tooltip=\"Package atomic provides low-level atomic memory primitives useful for implementing synchronization algorithms.\"];",
            " n19 [label=\"internal/cpu\", URL=\"https://godoc.org/internal/cpu\", tooltip=\"Package cpu implements processor feature detection used by the Go standard library.\"];",
            " n0 -> n1;",
            " n0 -> n2;",
            " n0 -> n3;",
            " n0 -> n4;",
            " n0 -> n5;",
            " n0 -> n6;",
            " n0 -> n7;",
            " n0 -> n8;",
            " n0 -> n9;",
            " n1 -> n10;",
            " n1 -> n2;",
            " n1 -> n8;",
            " n1 -> n9;",
            " n1 -> n11;",
            " n2 -> n11;",
            " n2 -> n7;",
            " n3 -> n4;",
            " n3 -> n5;",
            " n3 -> n6;",
            " n3 -> n8;",
            " n3 -> n9;",
            " n4 -> n12;",
            " n5 -> n10;",
            " n5 -> n13;",
            " n5 -> n9;",
            " n5 -> n11;",
            " n5 -> n14;",
            " n6 -> n2;",
            " n6 -> n7;",
            " n6 -> n15;",
            " n6 -> n11;",
            " n6 -> n10;",
            " n6 -> n8;",
            " n6 -> n9;",
            " n7 -> n16;",
            " n7 -> n17;",
            " n7 -> n18;",
            " n7 -> n15;",
            " n10 -> n19;",
            " n10 -> n15;",
            " n11 -> n12;",
            " n12 -> n17;",
            " n12 -> n15;",
            " n13 -> n15;",
            " n13 -> n19;",
            " n13 -> n14;",
            " n14 -> n15;",
            " n16 -> n15;",
            " n18 -> n15;",
            "}",
        ]),
    },
    {
        diagramType: "graphviz",
        default: false,
        description: "With clusters",
        title: "GraphViz",
        doc: "https://graphviz.org/gallery/",
        keywords: ["dot", "digraph", "directed", "node"],
        source: lines([
            "digraph G {",
            "",
            "\tsubgraph cluster_0 {",
            "\t\tstyle=filled;",
            "\t\tcolor=lightgrey;",
            "\t\tnode [style=filled,color=white];",
            "\t\ta0 -> a1 -> a2 -> a3;",
            "\t\tlabel = \"process #1\";",
            "\t}",
            "",
            "\tsubgraph cluster_1 {",
            "\t\tnode [style=filled];",
            "\t\tb0 -> b1 -> b2 -> b3;",
            "\t\tlabel = \"process #2\";",
            "\t\tcolor=blue",
            "\t}",
            "\tstart -> a0;",
            "\tstart -> b0;",
            "\ta1 -> b3;",
            "\tb2 -> a3;",
            "\ta3 -> a0;",
            "\ta3 -> end;",
            "\tb3 -> end;",
            "",
            "\tstart [shape=Mdiamond];",
            "\tend [shape=Msquare];",
            "}",
        ]),
    },
]);

export default graphviz;
