import { defineExamples, lines } from '../define';

const mermaid = defineExamples([
    {
        diagramType: "mermaid",
        default: true,
        description: "Default",
        title: "Mermaid",
        doc: "https://mermaid-js.github.io/mermaid/#/",
        keywords: ["UML", "activity", "diagram", "flowchart"],
        source: lines([
            "graph TD",
            "  A[ Anyone ] -->|Can help | B( Go to github.com/yuzutech/kroki )",
            "  B --> C{ How to contribute? }",
            "  C --> D[ Reporting bugs ]",
            "  C --> E[ Sharing ideas ]",
            "  C --> F[ Advocating ]",
            "",
        ], true),
    },
    {
        diagramType: "mermaid",
        default: false,
        description: "Flowchart",
        title: "Mermaid",
        doc: "https://mermaid-js.github.io/mermaid/#/flowchart",
        keywords: ["UML", "activity", "diagram", "flowchart"],
        source: lines([
            "flowchart TB",
            "    c1-->a2",
            "    subgraph one",
            "    a1-->a2",
            "    end",
            "    subgraph two",
            "    b1-->b2",
            "    end",
            "    subgraph three",
            "    c1-->c2",
            "    end",
            "    one --> two",
            "    three --> two",
            "    two --> c2",
        ]),
    },
    {
        diagramType: "mermaid",
        default: false,
        description: "Sequence diagram",
        title: "Mermaid",
        doc: "https://mermaid-js.github.io/mermaid/#/sequenceDiagram",
        keywords: ["UML", "sequence", "diagram"],
        source: lines([
            "sequenceDiagram",
            "    autonumber",
            "    Alice->>John: Hello John, how are you?",
            "    loop Healthcheck",
            "        John->>John: Fight against hypochondria",
            "    end",
            "    Note right of John: Rational thoughts!",
            "    John-->>Alice: Great!",
            "    John->>Bob: How about you?",
            "    Bob-->>John: Jolly good!",
        ]),
    },
    {
        diagramType: "mermaid",
        default: false,
        description: "Class diagram",
        title: "Mermaid",
        doc: "https://mermaid-js.github.io/mermaid/#/classDiagram",
        keywords: ["UML", "class", "diagram", "class", "object", "entity"],
        source: lines([
            "classDiagram",
            "  direction RL",
            "  class Student {",
            "    -idCard : IdCard",
            "  }",
            "  class IdCard{",
            "    -id : int",
            "    -name : string",
            "  }",
            "  class Bike{",
            "    -id : int",
            "    -name : string",
            "  }",
            "  Student \"1\" --o \"1\" IdCard : carries",
            "  Student \"1\" --o \"1\" Bike : rides",
        ]),
    },
    {
        diagramType: "mermaid",
        default: false,
        description: "State diagram",
        title: "Mermaid",
        doc: "https://mermaid-js.github.io/mermaid/#/stateDiagram",
        keywords: ["UML", "diagram", "state"],
        source: lines([
            "stateDiagram-v2",
            "    [*] --> First",
            "    First --> Second",
            "    First --> Third",
            "",
            "    state First {",
            "        [*] --> fir",
            "        fir --> [*]",
            "    }",
            "    state Second {",
            "        [*] --> sec",
            "        sec --> [*]",
            "    }",
            "    state Third {",
            "        [*] --> thi",
            "        thi --> [*]",
            "    }",
        ]),
    },
    {
        diagramType: "mermaid",
        default: false,
        description: "Entity Relationship diagram",
        title: "Mermaid",
        doc: "https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram",
        keywords: ["UML", "ERD", "diagram", "entity", "relation"],
        source: lines([
            "erDiagram",
            "    CAR ||--o{ NAMED-DRIVER : allows",
            "    CAR {",
            "        string registrationNumber",
            "        string make",
            "        string model",
            "    }",
            "    PERSON ||--o{ NAMED-DRIVER : is",
            "    PERSON {",
            "        string firstName",
            "        string lastName",
            "        int age",
            "    }",
        ]),
    },
    {
        diagramType: "mermaid",
        default: false,
        description: "User Journey diagram",
        title: "Mermaid",
        doc: "https://mermaid-js.github.io/mermaid/#/user-journey",
        keywords: ["diagram", "journey", "WTF"],
        source: lines([
            "journey",
            "    title My working day",
            "    section Go to work",
            "      Make tea: 5: Me",
            "      Go upstairs: 3: Me",
            "      Do work: 1: Me, Cat",
            "    section Go home",
            "      Go downstairs: 5: Me",
            "      Sit down: 5: Me",
        ]),
    },
    {
        diagramType: "mermaid",
        default: false,
        description: "Gantt diagram",
        title: "Mermaid",
        doc: "https://mermaid-js.github.io/mermaid/#/gantt",
        keywords: ["diagram", "gantt", "planing"],
        source: lines([
            "gantt",
            "    title A Gantt Diagram",
            "    dateFormat  YYYY-MM-DD",
            "    section Section",
            "    A task           :a1, 2014-01-01, 30d",
            "    Another task     :after a1  , 20d",
            "    section Another",
            "    Task in sec      :2014-01-12  , 12d",
            "    another task      : 24d",
        ]),
    },
    {
        diagramType: "mermaid",
        default: false,
        description: "Pie diagram",
        title: "Mermaid",
        doc: "https://mermaid-js.github.io/mermaid/#/pie",
        keywords: ["chart", "pie"],
        source: lines([
            "pie title Pets adopted by volunteers",
            "    \"Dogs\" : 386",
            "    \"Cats\" : 85",
            "    \"Rats\" : 15",
        ]),
    },
]);

export default mermaid;
