import { defineExamples, lines } from '../define';

const plantuml = defineExamples([
    {
        diagramType: "plantuml",
        default: true,
        description: "Default",
        title: "PlantUML",
        doc: "https://plantuml.com/en/",
        keywords: ["UML", "diagram", "component"],
        source: lines([
            "skinparam monochrome true",
            "skinparam ranksep 20",
            "skinparam dpi 150",
            "skinparam arrowThickness 0.7",
            "skinparam packageTitleAlignment left",
            "skinparam usecaseBorderThickness 0.4",
            "skinparam defaultFontSize 12",
            "skinparam rectangleBorderThickness 1",
            "",
            "rectangle \"Main\" {",
            "  (main.view)",
            "  (singleton)",
            "}",
            "rectangle \"Base\" {",
            "  (base.component)",
            "  (component)",
            "  (model)",
            "}",
            "rectangle \"<b>main.ts</b>\" as main_ts",
            "",
            "(component) ..> (base.component)",
            "main_ts ==> (main.view)",
            "(main.view) --> (component)",
            "(main.view) ...> (singleton)",
            "(singleton) ---> (model)",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Sequence diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/sequence-diagram",
        keywords: ["UML", "diagram", "sequence"],
        source: lines([
            "@startuml",
            "skin rose",
            "participant User",
            "",
            "User -> A: DoWork",
            "activate A #FFBBBB",
            "",
            "A -> A: Internal call",
            "activate A #DarkSalmon",
            "",
            "A -> B: << createRequest >>",
            "activate B",
            "",
            "B --> A: RequestCreated",
            "deactivate B",
            "deactivate A",
            "A -> User: Done",
            "deactivate A",
            "@enduml",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Use case diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/use-case-diagram",
        keywords: ["UML", "diagram", "use cases"],
        source: lines([
            "@startuml",
            "skin rose",
            "",
            ":Main Admin: as Admin",
            "(Use the application) as (Use)",
            "",
            "User -> (Start)",
            "User --> (Use)",
            "",
            "Admin ---> (Use)",
            "",
            "note right of Admin : This is an example.",
            "",
            "note right of (Use)",
            "  A note can also",
            "  be on several lines",
            "end note",
            "",
            "note \"This note is connected\\nto several objects.\" as N2",
            "(Start) .. N2",
            "N2 .. (Use)",
            "@enduml",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Class diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/class-diagram",
        keywords: ["UML", "diagram", "class"],
        source: lines([
            "@startuml",
            "skin rose",
            "",
            "abstract class AbstractList",
            "abstract AbstractCollection",
            "interface List",
            "interface Collection",
            "",
            "List <|-- AbstractList",
            "Collection <|-- AbstractCollection",
            "",
            "Collection <|- List",
            "AbstractCollection <|- AbstractList",
            "AbstractList <|-- ArrayList",
            "",
            "class ArrayList {",
            "  Object[] elementData",
            "  size()",
            "}",
            "",
            "enum TimeUnit {",
            "  DAYS",
            "  HOURS",
            "  MINUTES",
            "}",
            "",
            "annotation SuppressWarnings",
            "",
            "annotation Annotation {",
            "  annotation with members",
            "  String foo()",
            "  String bar()",
            "}",
            "",
            "",
            "@enduml",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Object diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/object-diagram",
        keywords: ["UML", "diagram", "object"],
        source: lines([
            "@startuml",
            "skin rose",
            "",
            "object London",
            "object Washington",
            "object Berlin",
            "object NewYork",
            "",
            "map CapitalCity {",
            " UK *-> London",
            " USA *--> Washington",
            " Germany *---> Berlin",
            "}",
            "",
            "NewYork --> CapitalCity::USA",
            "@enduml",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Activity diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/activity-diagram-beta",
        keywords: ["UML", "diagram", "activity"],
        source: lines([
            "@startuml",
            "skin rose",
            "",
            "start",
            ":ClickServlet.handleRequest();",
            ":new page;",
            "if (Page.onSecurityCheck) then (true)",
            "  :Page.onInit();",
            "  if (isForward?) then (no)",
            "    :Process controls;",
            "    if (continue processing?) then (no)",
            "      stop",
            "    endif",
            "",
            "    if (isPost?) then (yes)",
            "      :Page.onPost();",
            "    else (no)",
            "      :Page.onGet();",
            "    endif",
            "    :Page.onRender();",
            "  endif",
            "else (false)",
            "endif",
            "",
            "if (do redirect?) then (yes)",
            "  :redirect process;",
            "else",
            "  if (do forward?) then (yes)",
            "    :Forward request;",
            "  else (no)",
            "    :Render page template;",
            "  endif",
            "endif",
            "",
            "stop",
            "@enduml",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Component diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/component-diagram",
        keywords: ["UML", "diagram", "component"],
        source: lines([
            "@startuml",
            "skin rose",
            "skinparam packageBackgroundColor #ffffff",
            "skinparam packageBorderColor #333333",
            "",
            "package \"Some Group\" {",
            "  HTTP - [First Component]",
            "  [Another Component]",
            "}",
            "",
            "node \"Other Groups\" {",
            "  FTP - [Second Component]",
            "  [First Component] --> FTP",
            "}",
            "",
            "cloud {",
            "  [Example 1]",
            "}",
            "",
            "",
            "database \"MySql\" {",
            "  folder \"This is my folder\" {",
            "    [Folder 3]",
            "  }",
            "  frame \"Foo\" {",
            "    [Frame 4]",
            "  }",
            "}",
            "",
            "",
            "[Another Component] --> [Example 1]",
            "[Example 1] --> [Folder 3]",
            "[Folder 3] --> [Frame 4]",
            "",
            "@enduml",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Deployment diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/deployment-diagram",
        keywords: ["UML", "diagram", "deployment"],
        source: lines([
            "@startuml",
            "skin rose",
            "",
            "actor foo1",
            "actor foo2",
            "foo1 <-0-> foo2",
            "foo1 <-(0)-> foo2",
            " ",
            "(ac1) -le(0)-> left1",
            "ac1 -ri(0)-> right1",
            "ac1 .up(0).> up1",
            "ac1 ~up(0)~> up2",
            "ac1 -do(0)-> down1",
            "ac1 -do(0)-> down2",
            " ",
            "actor1 -0)- actor2",
            " ",
            "component comp1",
            "component comp2",
            "comp1 *-0)-+ comp2",
            "[comp3] <-->> [comp4]",
            "",
            "boundary b1",
            "control c1",
            "b1 -(0)- c1",
            "",
            "component comp1",
            "interface interf1",
            "comp1 #~~( interf1",
            "",
            ":mode1actor: -0)- fooa1",
            ":mode1actorl: -ri0)- foo1l",
            "",
            "[component1] 0)-(0-(0 [componentC]",
            "() component3 )-0-(0 \"foo\" [componentC]",
            "",
            "[aze1] #-->> [aze2]",
            "@enduml",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "State diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/state-diagram",
        keywords: ["UML", "diagram", "state"],
        source: lines([
            "@startuml",
            "skin rose",
            "",
            "[*] -> State1",
            "State1 --> State2 : Succeeded",
            "State1 --> [*] : Aborted",
            "State2 --> State3 : Succeeded",
            "State2 --> [*] : Aborted",
            "state State3 {",
            "  state \"Accumulate Enough Data\\nLong State Name\" as long1",
            "  long1 : Just a test",
            "  [*] --> long1",
            "  long1 --> long1 : New Data",
            "  long1 --> ProcessData : Enough Data",
            "}",
            "State3 --> State3 : Failed",
            "State3 --> [*] : Succeeded / Save Result",
            "State3 --> [*] : Aborted",
            "",
            "@enduml",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Network diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/nwdiag",
        keywords: ["network", "diagram", "nwdiag", "architecture", "subnet", "netmask", "router"],
        source: lines([
            "skin rose",
            "",
            "nwdiag {",
            "  network Sample_front {",
            "    address = \"192.168.10.0/24\";",
            "",
            "    // define group",
            "    group web {",
            "      web01 [address = \".1\"];",
            "      web02 [address = \".2\"];",
            "    }",
            "  }",
            "  network Sample_back {",
            "    address = \"192.168.20.0/24\";",
            "    web01 [address = \".1\"];",
            "    web02 [address = \".2\"];",
            "    db01 [address = \".101\"];",
            "    db02 [address = \".102\"];",
            "",
            "    // define network using defined nodes",
            "    group db {",
            "      db01;",
            "      db02;",
            "    }",
            "  }",
            "}",
            "",
        ], true),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "JSON diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/json",
        keywords: ["JSON", "diagram", "object", "instance", "tree"],
        source: lines([
            "@startjson",
            "{",
            "  \"firstName\": \"John\",",
            "  \"lastName\": \"Smith\",",
            "  \"isAlive\": true,",
            "  \"age\": 27,",
            "  \"address\": {",
            "    \"streetAddress\": \"21 2nd Street\",",
            "    \"city\": \"New York\",",
            "    \"state\": \"NY\",",
            "    \"postalCode\": \"10021-3100\"",
            "  },",
            "  \"phoneNumbers\": [",
            "    {",
            "      \"type\": \"home\",",
            "      \"number\": \"212 555-1234\"",
            "    },",
            "    {",
            "      \"type\": \"office\",",
            "      \"number\": \"646 555-4567\"",
            "    }",
            "  ],",
            "  \"children\": [],",
            "  \"spouse\": null",
            "}",
            "@endjson",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "YAML diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/yaml",
        keywords: ["YAML", "diagram", "object", "instance", "tree"],
        source: lines([
            "@startyaml",
            "doe: \"a deer, a female deer\"",
            "ray: \"a drop of golden sun\"",
            "pi: 3.14159",
            "xmas: true",
            "french-hens: 3",
            "calling-birds: ",
            "\t- huey",
            "\t- dewey",
            "\t- louie",
            "\t- fred",
            "xmas-fifth-day: ",
            "\tcalling-birds: four",
            "\tfrench-hens: 3",
            "\tgolden-rings: 5",
            "\tpartridges: ",
            "\t\tcount: 1",
            "\t\tlocation: \"a pear tree\"",
            "\tturtle-doves: two",
            "@endyaml",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Gantt diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/gantt-diagram",
        keywords: ["diagram", "gantt", "planing"],
        source: lines([
            "@startgantt",
            "Project starts the 5th of december 2018",
            "saturday are closed",
            "sunday are closed",
            "2018/12/29 is opened",
            "[Prototype design] lasts 10 days",
            "[Prototype design] pauses on 2018/12/13",
            "[Prototype design] pauses on 2018/12/14",
            "[Prototype design] pauses on monday",
            "[Test prototype] starts at [Prototype design]'s end and lasts 2 weeks",
            "@endgantt",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Salt mockup",
        title: "PlantUML",
        doc: "https://plantuml.com/en/salt",
        keywords: ["salt", "mockup", "wireframe", "GUI", "graphical interface", ""],
        source: lines([
            "@startsalt",
            "{+",
            "{/ <b>General | Fullscreen | Behavior | Saving }",
            "{",
            "{ Open image in: | ^Smart Mode^ }",
            "[X] Smooth images when zoomed",
            "[X] Confirm image deletion",
            "[ ] Show hidden images",
            "}",
            "[Close]",
            "}",
            "@endsalt",
        ]),
    },
    {
        diagramType: "plantuml",
        default: false,
        description: "Timing diagram",
        title: "PlantUML",
        doc: "https://plantuml.com/en/timing-diagram",
        keywords: ["diagram", "timing", "wave", "electric", "signal"],
        source: lines([
            "@startuml",
            "robust \"Web Browser\" as WB",
            "concise \"Web User\" as WU",
            "",
            "WB is Initializing",
            "WU is Absent",
            "",
            "@WB",
            "0 is idle",
            "+200 is Processing",
            "+100 is Waiting",
            "WB@0 <-> @50 : {50 ms lag}",
            "",
            "@WU",
            "0 is Waiting",
            "+500 is ok",
            "@200 <-> @+150 : {150 ms}",
            "@enduml",
        ]),
    },
]);

export default plantuml;
