import { defineExamples, lines } from '../define';

const tikz = defineExamples([
    {
        diagramType: "tikz",
        default: true,
        description: "Default",
        title: "TikZ",
        keywords: ["TeX", "LaTex", "Geometry", "vector", "angles"],
        source: lines([
            "% Find more inspiring examples at: https://tikz.net/",
            "",
            "\\documentclass{article}",
            "\\usepackage{tikz}",
            "\\usepackage{tikz-3dplot}",
            "\\usetikzlibrary{math}",
            "\\usepackage[active,tightpage]{preview}",
            "\\PreviewEnvironment{tikzpicture}",
            "\\setlength\\PreviewBorder{0.125pt}",
            "%",
            "% File name: directional-angles.tex",
            "% Description: ",
            "% The directional angles of a vector are geometrically represented.",
            "% ",
            "% Date of creation: July, 25th, 2021.",
            "% Date of last modification: October, 9th, 2022.",
            "% Author: Efra�n Soto Apolinar.",
            "% https://www.aprendematematicas.org.mx/author/efrain-soto-apolinar/instructing-courses/",
            "% Source: page 11 of the ",
            "% Glosario Ilustrado de Matem\\'aticas Escolares.",
            "% https://tinyurl.com/5udm2ufy",
            "%",
            "% Terms of use:",
            "% According to TikZ.net",
            "% https://creativecommons.org/licenses/by-nc-sa/4.0/",
            "% Your commitment to the terms of use is greatly appreciated.",
            "%",
            "\\begin{document}",
            "\t\\tdplotsetmaincoords{80}{120}",
            "\t%",
            "\t\\begin{tikzpicture}[tdplot_main_coords,scale=1.5,transform shape]",
            "\t\t% Indicate the components of the vector in rectangular coordinates",
            "\t\t\\pgfmathsetmacro{\\ux}{4}",
            "\t\t\\pgfmathsetmacro{\\uy}{4}",
            "\t\t\\pgfmathsetmacro{\\uz}{3}",
            "\t\t% Length of each axis",
            "\t\t\\pgfmathsetmacro{\\ejex}{\\ux+0.5}",
            "\t\t\\pgfmathsetmacro{\\ejey}{\\uy+0.5}",
            "\t\t\\pgfmathsetmacro{\\ejez}{\\uz+0.5}",
            "\t\t\\pgfmathsetmacro{\\umag}{sqrt(\\ux*\\ux+\\uy*\\uy+\\uz*\\uz)} % Magnitude of vector $\\vec{u}$",
            "\t\t% Compute the angle $\\theta$",
            "\t\t\\pgfmathsetmacro{\\angthetax}{pi*atan(\\uy/\\ux)/180}",
            "\t\t\\pgfmathsetmacro{\\angthetay}{pi*atan(\\ux/\\uz)/180}",
            "\t\t\\pgfmathsetmacro{\\angthetaz}{pi*atan(\\uz/\\uy)/180}",
            "\t\t% Compute the angle $\\phi$",
            "\t\t\\pgfmathsetmacro{\\angphix}{pi*acos(\\ux/\\umag)/180}",
            "\t\t\\pgfmathsetmacro{\\angphiy}{pi*acos(\\uy/\\umag)/180}",
            "\t\t\\pgfmathsetmacro{\\angphiz}{pi*acos(\\uz/\\umag)/180}",
            "\t\t% Compute rho sin(phi) to simplify computations",
            "\t\t\\pgfmathsetmacro{\\costz}{cos(\\angthetax r)}\t",
            "\t\t\\pgfmathsetmacro{\\sintz}{sin(\\angthetax r)}\t",
            "\t\t\\pgfmathsetmacro{\\costy}{cos(\\angthetay r)}\t",
            "\t\t\\pgfmathsetmacro{\\sinty}{sin(\\angthetay r)}\t",
            "\t\t\\pgfmathsetmacro{\\costx}{cos(\\angthetaz r)}\t",
            "\t\t\\pgfmathsetmacro{\\sintx}{sin(\\angthetaz r)}\t",
            "\t\t% Coordinate axis",
            "\t\t\\draw[thick,->] (0,0,0) -- (\\ejex,0,0) node[below left] {$x$};",
            "\t\t\\draw[thick,->] (0,0,0) -- (0,\\ejey,0) node[right] {$y$};",
            "\t\t\\draw[thick,->] (0,0,0) -- (0,0,\\ejez) node[above] {$z$};",
            "\t\t% Projections of the components in the axis",
            "\t\t\\draw[gray,very thin,opacity=0.5] (0,0,0) -- (\\ux,0,0) -- (\\ux,\\uy,0) -- (0,\\uy,0) -- (0,0,0);\t% face on the plane z = 0",
            "\t\t\\draw[gray,very thin,opacity=0.5] (0,0,\\uz) -- (\\ux,0,\\uz) -- (\\ux,\\uy,\\uz) -- (0,\\uy,\\uz) -- (0,0,\\uz);\t% face on the plane z = \\uz",
            "\t\t\\draw[gray,very thin,opacity=0.5] (0,0,0) -- (0,0,\\uz) -- (\\ux,0,\\uz) -- (\\ux,0,0) -- (0,0,0);\t% face on the plane y = 0",
            "\t\t\\draw[gray,very thin,opacity=0.5] (0,\\uy,0) -- (0,\\uy,\\uz) -- (\\ux,\\uy,\\uz) -- (\\ux,\\uy,0) -- (0,\\uy,0);\t% face on the plane y = \\uy",
            "\t\t\\draw[gray,very thin,opacity=0.5] (0,0,0) -- (0,\\uy,0) -- (0,\\uy,\\uz) -- (0,0,\\uz) -- (0,0,0); % face on the plane x = 0",
            "\t\t\\draw[gray,very thin,opacity=0.5] (\\ux,0,0) -- (\\ux,\\uy,0) -- (\\ux,\\uy,\\uz) -- (\\ux,0,\\uz) -- (\\ux,0,0); % face on the plane x = \\ux",
            "\t\t% Arc indicating the angle $\\alpha$",
            "\t\t% (angle formed by the vector $\\vec{v}$ and the $x$ axis)",
            "\t\t\\draw[red,thick] plot[domain=0:\\angphix,smooth,variable=\\t] ({cos(\\t r)},{sin(\\t r)*\\costx},{sin(\\t r)*\\sintx});",
            "\t\t% Arc indicating the angle $\\beta$",
            "\t\t% (angle formed by the vector $\\vec{v}$ and the $y$ axis)",
            "\t\t\\draw[red,thick] plot[domain=0:\\angphiy,smooth,variable=\\t] ({sin(\\t r)*\\sinty},{cos(\\t r)},{sin(\\t r)*\\costy});",
            "\t\t% Arc indicating the angle $\\gamma$",
            "\t\t% (angle formed by the vector $\\vec{v}$ and the $z$ axis)",
            "\t\t\\draw[red,thick] plot[domain=0:\\angphiz,smooth,variable=\\t] ({sin(\\t r)*\\costz},{sin(\\t r)*\\sintz},{cos(\\t r)});",
            "\t\t% Vector $\\vec{u}$",
            "\t\t\\draw[blue,thick,->] (0,0,0) -- (\\ux,\\uy,\\uz) node [below right] {$\\vec{u}$};",
            "\t\t% Nodes indicating the direction angles",
            "\t\t\\pgfmathsetmacro{\\xa}{1.85*cos(0.5*\\angphix r)}",
            "\t\t\\pgfmathsetmacro{\\ya}{1.85*sin(0.5*\\angphix r)*\\costx}",
            "\t\t\\pgfmathsetmacro{\\za}{1.85*sin(0.5*\\angphiz r)*\\sintx}",
            "\t\t\\node[red] at (\\xa,\\ya,\\za) {\\footnotesize$\\alpha$};",
            "\t\t%",
            "\t\t\\pgfmathsetmacro{\\xb}{1.5*sin(0.5*\\angphiy r)*\\sinty}",
            "\t\t\\pgfmathsetmacro{\\yb}{1.5*cos(0.5*\\angphiy r)}",
            "\t\t\\pgfmathsetmacro{\\zb}{1.5*sin(0.5*\\angphiy r)*\\costy}",
            "\t\t\\node[red] at (\\xb,\\yb,\\zb) {\\footnotesize$\\beta$};",
            "\t\t%",
            "\t\t\\pgfmathsetmacro{\\xc}{1.5*sin(0.5*\\angphiz r)*\\costz}",
            "\t\t\\pgfmathsetmacro{\\yc}{1.5*sin(0.5*\\angphiz r)*\\sintz}",
            "\t\t\\pgfmathsetmacro{\\zc}{1.5*cos(0.5*\\angphiz r)}",
            "\t\t\\node[red] at (\\xc,\\yc,\\zc) {\\footnotesize$\\gamma$};",
            "\t\t%",
            "\t\\end{tikzpicture}",
            "\t%",
            "\\end{document}",
        ]),
    },
    {
        diagramType: "tikz",
        default: false,
        description: "Mecanics",
        title: "TikZ",
        keywords: ["TeX", "LaTex", "Mecanics", "forces"],
        source: lines([
            "% Find more inspiring examples at: https://tikz.net/",
            "",
            "% Author: Izaak Neutelings (September 2020)",
            "% Inspiration: https://tex.stackexchange.com/questions/25531/adding-underbrace-in-tikz",
            "\\documentclass[border=3pt,tikz]{standalone}",
            "\\usepackage{physics}",
            "\\usepackage{ifthen}",
            "\\usepackage{tikz}",
            "\\usetikzlibrary{patterns}",
            "\\tikzset{>=latex} % for LaTeX arrow head",
            "",
            "\\colorlet{myred}{red!65!black}",
            "\\colorlet{acol}{red!50!blue!80!black!80}",
            "\\tikzstyle{ground}=[preaction={fill,top color=black!10,bottom color=black!5,shading angle=20},",
            "                    fill,pattern=north east lines,draw=none,minimum width=0.3,minimum height=0.6]",
            "\\tikzstyle{mass}=[line width=0.6,red!30!black,fill=red!40!black!10,rounded corners=1,",
            "                  top color=red!40!black!20,bottom color=red!40!black!10,shading angle=20]",
            "\\tikzstyle{rope}=[brown!70!black,line width=1.2,line cap=round] %very thick",
            "",
            "% FORCES SWITCH",
            "\\tikzstyle{force}=[->,myred,thick,line cap=round]",
            "\\newcommand{\\vbF}{\\vb{F}}",
            "\\newboolean{showforces}",
            "\\setboolean{showforces}{true}",
            "",
            "",
            "\\begin{document}",
            "",
            "% HORIZONTAL ground - lift",
            "\\begin{tikzpicture}[scale=3,transform shape]",
            "  \\def\\W{2.1}  % ground width",
            "  \\def\\D{0.2}  % ground depth",
            "  \\def\\h{0.6}  % mass height",
            "  \\def\\w{0.7}  % mass width",
            "  \\def\\H{2.0}  % human height",
            "  \\def\\mx{-0.12*\\W} % mass x coordinate",
            "  ",
            "  % SETUP",
            "  \\draw[ground] (-\\W/2,0) rectangle++ (\\W,-\\D);",
            "  \\draw (-\\W/2,0) --++ (\\W,0);",
            "  \\draw[rope]  (\\mx,\\h) -- (\\mx*0.98,0.6*\\H) coordinate (RH);",
            "  \\draw[mass] (\\mx-\\w/2,0) rectangle++ (\\w,\\h) node[midway] {$m$};",
            "  ",
            "  % FORCES",
            "  \\ifthenelse{\\boolean{showforces}}{",
            "    \\draw[->] (0.42*\\W,0.5*\\h) --++ (0,0.9*\\h) node[below=4,right=0] {$y$};",
            "    \\draw[force] (\\mx-0.15*\\w,0.9*\\h) --++ (0, 1.0*\\h) node[above left=-3] {$\\vbF$};",
            "    \\draw[force] (\\mx-0.35*\\w,0.0*\\h) --++ (0, 0.7*\\h) node[left] {$\\vbF_\\mathrm{N}$};",
            "    \\draw[force] (\\mx+0.30*\\w,0.5*\\h) --++ (0,-1.4*\\h) node[right=5,below=-2] {$\\vbF_\\mathrm{g} = -mg\\vu{y}$};",
            "  }{}",
            "  ",
            "  % PERSON",
            "  \\draw[thick] (0.17*\\W,\\H) circle (0.3) coordinate (H);",
            "  \\draw[thick] (H)++(-90:0.3) coordinate (N) to[out=-85,in=85]++ (0,-0.40*\\H) coordinate (P);",
            "  \\draw[thick,line cap=round] (N)++(-85:0.03) to[out=-115,in=3] (RH);",
            "  \\draw[thick,line cap=round] (N)++(-85:0.03) to[out=-60,in=90]++ ( 0.08*\\W,-0.4*\\H);",
            "  \\draw[thick] (P) to[out=-110,in=85] (0.09*\\W,0);",
            "  \\draw[thick] (P) to[out=-80,in=108] (0.23*\\W,0);",
            "  ",
            "\\end{tikzpicture}",
            "",
            "\\end{document}",
        ]),
    },
    {
        diagramType: "tikz",
        default: false,
        description: "Mathematics",
        title: "TikZ",
        keywords: ["TeX", "LaTex", "Mathematics", "formula", "function"],
        source: lines([
            "% Find more inspiring examples at: https://tikz.net/",
            "",
            "\\documentclass{article}",
            "\\usepackage{tikz}",
            "\\usepackage{tikz-3dplot}",
            "\\usetikzlibrary{math}",
            "\\usepackage[active,tightpage]{preview}",
            "\\PreviewEnvironment{tikzpicture}",
            "\\setlength\\PreviewBorder{0.125pt}",
            "%",
            "% File name: linear-approximation-2d.tex",
            "% Description: ",
            "% The linear approximation for a function of one variable $y = f(x)$ is shown.",
            "% ",
            "% Date of creation: March, 7th, 2021.",
            "% Date of last modification: October, 9th, 2022.",
            "% Author: Efra�n Soto Apolinar.",
            "% https://www.aprendematematicas.org.mx/author/efrain-soto-apolinar/instructing-courses/",
            "% Source: page 15 of the ",
            "% Glosario Ilustrado de Matem\\'aticas Escolares.",
            "% https://tinyurl.com/5udm2ufy",
            "%",
            "% Terms of use:",
            "% According to TikZ.net",
            "% https://creativecommons.org/licenses/by-nc-sa/4.0/",
            "% Your commitment to the terms of use is greatly appreciated.",
            "",
            "\\begin{document}",
            "\t%",
            "\t\\begin{tikzpicture}[scale=1.8,transform shape]",
            "\t\\pgfmathsetmacro{\\xi}{2.5}",
            "\t\\pgfmathsetmacro{\\step}{1.0}",
            "\t\\pgfmathsetmacro{\\xf}{\\xi+\\step}",
            "\t\\pgfmathsetmacro{\\yi}{exp(0.35*\\xi)}",
            "\t\\pgfmathsetmacro{\\yf}{exp(0.35*\\xf)}",
            "\t\\pgfmathsetmacro{\\yfa}{0.35*exp(0.35*\\xi)*(\\xf-\\xi)+\\yi}",
            "\t\\pgfmathsetmacro{\\ym}{0.5*(\\yi+\\yfa)}",
            "\t% Coordinate axis",
            "\t\\draw[thick,->] (-0.125,0) -- (5,0) node [right]{$x$};",
            "\t\\draw[thick,->] (0,-0.125) -- (0,4.5) node [above]{$y$};",
            "\t% Graph of the function $y = y(x)$",
            "\t\\draw[red,thick,->] plot[domain=0:4.25] (\\x,{exp(0.35*\\x)}) node[right]{\\footnotesize$y = y(x)$};",
            "\t% The linear approximation",
            "\t\\draw[blue,very thick] (\\xi,\\yi) -- (\\xf,\\yfa) ",
            "\t\t-- (\\xf,\\yi) ",
            "\t\t-- (\\xi,\\yi); \t",
            "\t%",
            "\t\\draw[dash dot] (\\xi,0) node[black,below] {\\footnotesize$x$} -- (\\xi,\\yi) ",
            "\t\t\t-- (0,\\yi) node[left] {\\footnotesize$f(x)$};",
            "\t\\draw[dash dot] (\\xf,0) node[black,below]{\\footnotesize$x + \\Delta x$} ",
            "\t\t\t-- (\\xf,\\yf) ",
            "\t\t\t-- (0,\\yf) node[left] {\\footnotesize$f(x + \\Delta x)$};",
            "\t% Indication of points, measures and lengths",
            "\t\\draw[dash dot dot,shift={(\\xf,\\yi)}] (0,0) -- (2,0);",
            "\t\\draw[dash dot dot,shift={(\\xf,\\yfa)}] (0,0) -- (2,0);",
            "\t\\draw[thick,<->,shift={(0,0)}] (\\xi,\\yi-0.5) -- (\\xf,\\yi-0.5) node [midway,fill=white] {\\footnotesize$\\Delta x$};",
            "\t\\draw[thick,<->,shift={(0,0)}] (\\xf+1.0,\\yi) -- (\\xf+1.0,\\yfa) node [midway,fill=white] {\\footnotesize$f'(x) \\cdot \\Delta x$};",
            "\t\\draw[thick,<->,shift={(0.55*\\xi,0)}] (0,\\yi) -- (0,\\yf) node [midway,fill=white] {\\footnotesize$f(x + \\Delta x) - f(x)$};",
            "\t\\draw[thick,<->,shift={(0,0)}] (\\xf+1.0,\\yi) -- (\\xf+1.0,0) node [midway,fill=white] {\\footnotesize$f(x)$};",
            "\t\\end{tikzpicture}",
            "\t%",
            "\\end{document}",
        ]),
    },
    {
        diagramType: "tikz",
        default: false,
        description: "Electric Engineering",
        title: "TikZ",
        keywords: ["TeX", "LaTex", "Electric Engineering", "circuit", "resistors"],
        source: lines([
            "% Find more inspiring examples at: https://tikz.net/",
            "",
            "\\documentclass[border=3pt]{standalone}",
            "",
            "% Circuits",
            "\\usepackage[european,s traightvoltages, RPvoltages, americanresistor, americaninductors]{circuitikz}",
            "\\tikzset{every picture/.style={line width=0.2mm}}",
            "",
            "% Notation",
            "\\usepackage{amsmath}",
            "",
            "% Tikz Library",
            "\\usetikzlibrary{calc}",
            "",
            "% Bipoles Specifications",
            "\\ctikzset{bipoles/thickness=1.2, label distance=1mm, voltage shift = 1}",
            "",
            "% Arrows Above Compenents",
            "% Source: https://tex.stackexchange.com/questions/574576/circuitikz-straight-voltage-arrows-with-fixed-length",
            "\\newcommand{\\fixedvlen}[3][0.4cm]{% [semilength]{node}{label}",
            "    % get the center of the standard arrow",
            "    \\coordinate (#2-Vcenter) at ($(#2-Vfrom)!0.5!(#2-Vto)$);",
            "    % draw an arrow of a fixed size around that center and on the same line",
            "    \\draw[-{Triangle[round,open]}] ($(#2-Vcenter)!#1!(#2-Vfrom)$) -- ($(#2-Vcenter)!#1!(#2-Vto)$);",
            "    % position the label as it where if standard voltages were used",
            "    \\node[ anchor=\\ctikzgetanchor{#2}{Vlab}] at (#2-Vlab) {#3};",
            "}",
            "\\newcommand{\\fixedvlendashed}[3][0.75cm]{% [semilength]{node}{label}",
            "    % get the center of the standard arrow",
            "    \\coordinate (#2-Vcenter) at ($(#2-Vfrom)!0.5!(#2-Vto)$);",
            "    % draw an arrow of a fixed size around that center and on the same line",
            "    \\draw[dashed,-{Triangle[round,open]}] ($(#2-Vcenter)!#1!(#2-Vfrom)$) -- ($(#2-Vcenter)!#1!(#2-Vto)$);",
            "    % position the label as it where if standard voltages were used",
            "    \\node[ anchor=\\ctikzgetanchor{#2}{Vlab}] at (#2-Vlab) {#3};",
            "}",
            "",
            "\\begin{document}",
            "",
            "\\begin{circuitikz}[scale=1.5,transform shape]",
            "%\t%Grid",
            "%\t\\def\\length{6}",
            "%\t\\draw[thin, dotted] (-\\length,-\\length) grid (\\length,\\length);",
            "%\t\\foreach \\i in {1,...,\\length}",
            "%\t{",
            "%\t\t\\node at (\\i,-2ex) {\\i};",
            "%\t\t\\node at (-\\i,-2ex) {-\\i};\t",
            "%\t}",
            "%\t\\foreach \\i in {1,...,\\length}",
            "%\t{",
            "%\t\t\\node at (-2ex,\\i) {\\i};\t",
            "%\t\t\\node at (-2ex,-\\i) {-\\i};\t",
            "%\t}",
            "%\t\\node at (-2ex,-2ex) {0};",
            "\t",
            "\t%Circuit",
            "\t\\node[op amp, noinv input up] at (0,0) (opamp) {};",
            "\t\\node[ground] at (-4.69,-5.5) (ground) {};",
            "\t\\draw (opamp.-) -- ++(-1.15,0) -- ++(0,-2) to[R, l_=$R_1$] ++(0,-2.5) to[short,-*] ++(-2.35,0);",
            "\t\\draw (opamp.+) -- ++(-3.5,0) to[sV, l_=$v_\\text{IN}$,] ++(0,-3) -- (ground);",
            "\t\\draw (1.66,0) to[short,*-] ++(0,-2.5) to[R, l^=$R_2$, -*] ++(-4,0);",
            "\t\\draw (opamp.out) to[short,-*] ++(1.5,0) node[shift={(0.6,0)}] {$v_\\text{O}$};",
            "\t\\draw[-latex] (opamp.up) -- ++(0,0.5) node[above] {$V_+$};",
            "\t\\draw[-latex] (opamp.down) -- ++(0,-0.5) node[below] {$V_-$};",
            "%\t\\draw[-{Triangle[round]}] ($(opamp.-)+(-0.15,0)$) -- +(+0.2,0) node[below] {\\scriptsize$i_-$};",
            "%\t\\draw[-{Triangle[round]}] ($(opamp.+)+(-0.15,0)$) -- +(+0.2,0) node[above] {\\scriptsize$i_+$};",
            "\t",
            "\t%Voltage",
            "%\t\\fixedvlen[0.4]{R1}{$V_{R_1}$};",
            "%\t\\fixedvlen[0.4]{R2}{$V_{R_2}$};",
            "\t",
            "\t%Nodes",
            "\t\\node[shift={(0,-0.3)}] at (opamp.-) {\\scriptsize$v_-$};",
            "\t\\node[shift={(0,+0.3)}] at (opamp.+) {\\scriptsize$v_+$};",
            "",
            "\\end{circuitikz}",
            "\t",
            "\\end{document}",
        ]),
    },
    {
        diagramType: "tikz",
        default: false,
        description: "Optical illusion",
        title: "TikZ",
        keywords: ["TeX", "LaTex", "Optical illusion", "squares", "simple schema"],
        source: lines([
            "% Find more inspiring examples at: https://tikz.net/",
            "",
            "\\documentclass[tikz,border=10pt]{standalone}",
            "\\begin{document}",
            "% definition of the pieces, just to show that in",
            "% both configurations the same ones are used",
            "\\newcommand{\\bluetriangle}[1][]{",
            "  \\draw[fill=blue,#1]",
            "       (0,0)--( 8,0)--( 8,3)--cycle;}",
            "\\newcommand{\\yellowtriangle}[1][]{",
            "  \\draw[fill=yellow,#1]",
            "       (8,3)--(13,3)--(13,5)--cycle;}",
            "\\newcommand{\\redpolygon}[1][]{",
            "  \\draw[fill=red,#1]",
            "       (8,0)--(13,0)--(13,2)--(10,2)--(10,1)--(8,1)--cycle;}",
            "\\newcommand{\\greenpolygon}[1][]{",
            "  \\draw[fill=green,#1]",
            "       (8,1)--(10,1)--(10,2)--(13,2)--(13,3)--(8,3)--cycle;}",
            "\\begin{tikzpicture}[x=0.5cm,y=0.5cm,thick]",
            "% the grid",
            "  \\draw[help lines,step=1] (-1,-1) grid (14,12);",
            "% the complete triangle",
            "    \\bluetriangle",
            "    \\yellowtriangle",
            "    \\redpolygon",
            "    \\greenpolygon",
            "% the missing square triangle",
            "  \\begin{scope}[yshift=3cm]",
            "    \\bluetriangle  [shift={( 5, 2)}]",
            "    \\yellowtriangle[shift={(-8,-3)}]",
            "    \\redpolygon    [shift={( 0, 0)}]",
            "    \\greenpolygon  [shift={(-3,-1)}]",
            "  \\end{scope}",
            "% the solution (uncomment next line and close in)",
            "%    \\draw[very thin,red] (0,0)--(13,5) {[yshift=3cm] (0,0)--(13,5)};",
            "\\end{tikzpicture}",
            "\\end{document}",
        ]),
    },
    {
        diagramType: "tikz",
        default: false,
        description: "Neural networks",
        title: "TikZ",
        keywords: ["TeX", "LaTex", "Neural networks", "abstract graphs"],
        source: lines([
            "% Find more inspiring examples at: https://tikz.net/",
            "",
            "% TikZ-reproduction of fig. 1 from the paper MADE: Masked Autoencoder for Distribution Estimation (https://arxiv.org/abs/1502.03509).",
            "",
            "\\documentclass[tikz]{standalone}",
            "",
            "\\usepackage{xstring}",
            "",
            "\\usetikzlibrary{calc,positioning}",
            "",
            "\\newcommand\\drawNodes[2]{",
            "  % #1 (str): namespace",
            "  % #2 (list[list[str]]): list of labels to print in the node of each neuron",
            "  \\foreach \\neurons [count=\\lyrIdx] in #2 {",
            "    \\StrCount{\\neurons}{,}[\\lyrLength] % use xstring package to save each layer size into \\lyrLength macro",
            "    \\foreach \\n [count=\\nIdx] in \\neurons",
            "      \\node[neuron] (#1-\\lyrIdx-\\nIdx) at (\\lyrLength/2-\\nIdx, 1.5*\\lyrIdx) {\\n};",
            "  }",
            "}",
            "",
            "\\newcommand\\denselyConnectNodes[2]{",
            "  % #1 (str): namespace",
            "  % #2 (list[int]): number of nodes in each layer",
            "  \\foreach \\n [count=\\lyrIdx, remember=\\lyrIdx as \\previdx, remember=\\n as \\prevn] in #2 {",
            "    \\foreach \\y in {1,...,\\n} {",
            "      \\ifnum \\lyrIdx > 1",
            "        \\foreach \\x in {1,...,\\prevn}",
            "          \\draw[->] (#1-\\previdx-\\x) -- (#1-\\lyrIdx-\\y);",
            "      \\fi",
            "    }",
            "  }",
            "}",
            "",
            "\\newcommand\\connectSomeNodes[2]{",
            "  % #1 (str): namespace",
            "  % #2 (list[list[list[int]]]): for each node in each layer, list all connected nodes in the next layer",
            "  \\foreach \\layer [count=\\lyrIdx, evaluate=\\lyrIdx as \\nextLyr using int(\\lyrIdx+1)] in #2",
            "    \\foreach \\neuron [count=\\nIdx] in \\layer",
            "        \\foreach \\edge in \\neuron",
            "          \\draw[->] (#1-\\lyrIdx-\\nIdx) -- (#1-\\nextLyr-\\edge);",
            "}",
            "",
            "\\begin{document}",
            "\\begin{tikzpicture}[",
            "    shorten >=1pt, shorten <=1pt,",
            "    neuron/.style={circle, draw, minimum size=4ex, thick},",
            "    legend/.style={font=\\large\\bfseries},",
            "  ]",
            "",
            "  % Fully-connected neural net",
            "  \\drawNodes{fcnn}{{{,,}, {,,,}, {,,,}, {,,}}}",
            "  \\denselyConnectNodes{fcnn}{{3, 4, 4, 3}}",
            "",
            "  \\path (fcnn-1-1) -- (fcnn-2-1) node[midway, right=1ex] (W1) {$W_1$};",
            "  \\path (fcnn-2-1) -- (fcnn-3-1) node[midway, right=1ex] (W2) {$W_2$};",
            "  \\path (fcnn-3-1) -- (fcnn-4-1) node[midway, right=1ex] (V) {$V$};",
            "",
            "  % MADE net",
            "  \\begin{scope}[xshift=9cm]",
            "    \\drawNodes{made}{{{3,1,2}, {2,1,2,2}, {1,2,2,1}, {3,1,2}}}",
            "    \\connectSomeNodes{made}{{",
            "          {{}, {1,2,3,4}, {1,3,4}},",
            "          {{2,3}, {1,2,3,4}, {2,3}, {2,3}},",
            "          {{1,3}, {1}, {1}, {1,3}},",
            "        }}",
            "  \\end{scope}",
            "",
            "  % Input + output labels",
            "  \\foreach \\idx in {1,2,3} {",
            "      \\node[below=0 of fcnn-1-\\idx] {$x_\\idx$};",
            "      \\node[above=0 of fcnn-4-\\idx] {$\\hat x_\\idx$};",
            "      \\node[below=0 of made-1-\\idx] {$x_\\idx$};",
            "    }",
            "",
            "  % MADE output labels",
            "  \\node[xshift=2.5ex, above=0 of made-4-1] {$p(x_3|x_2)$};",
            "  \\node[above=0 of made-4-2] {$p(x_2)$};",
            "  \\node[xshift=-4ex, above=0 of made-4-3] {$p(x_1|x_2,x_3)$};",
            "",
            "  % Bottom legend",
            "  \\node[legend, below=of fcnn-1-2] (encoder) {autoencoder};",
            "  \\node[legend, below=of made-1-2] (made) {MADE};",
            "  \\node[legend, right=2.5cm of encoder] (masks) {masks};",
            "  \\node[legend, yshift=-1pt] (masks) at ($(encoder)!0.55!(masks)$) {\\texttimes};",
            "  \\node[legend, yshift=-1pt] (masks) at ($(masks)!0.65!(made)$) {$\\longrightarrow$};",
            "",
            "  % Mask matrices",
            "  \\begin{scope}[shift={(3cm,5cm)}, scale=0.4]",
            "    \\draw (0,0) grid (4,3);",
            "    \\node at (-1.8,1.5) {$M_V =$};",
            "    \\fill[black] (0,1) rectangle ++(4,1);",
            "    \\fill[black] (1,0) rectangle ++(2,1);",
            "",
            "    \\begin{scope}[yshift=-5cm]",
            "      \\draw (0,0) grid (4,4);",
            "      \\node at (-1.8,2) {$M_{W_2} =$};",
            "      \\fill[black] (0,0) rectangle ++(1,1);",
            "      \\fill[black] (0,3) rectangle ++(1,1);",
            "      \\fill[black] (2,0) rectangle ++(2,1);",
            "      \\fill[black] (2,3) rectangle ++(2,1);",
            "    \\end{scope}",
            "",
            "    \\begin{scope}[yshift=-10cm]",
            "      \\draw (0,0) grid (3,4);",
            "      \\node at (-1.8,2) {$M_{W_1} =$};",
            "      \\fill[black] (0,0) rectangle ++(1,4);",
            "      \\fill[black] (2,2) rectangle ++(1,1);",
            "    \\end{scope}",
            "",
            "  \\end{scope}",
            "",
            "\\end{tikzpicture}",
            "\\end{document}",
        ]),
    },
    {
        diagramType: "tikz",
        default: false,
        description: "Timelines",
        title: "TikZ",
        keywords: ["TeX", "LaTex", "Timelines", "chronological events"],
        source: lines([
            "% Find more inspiring examples at: https://tikz.net/",
            "",
            "% Author: Izaak Neutelings (July 2017)",
            "% Timelines & energy scales of particle physics",
            "\\documentclass[border=1pt,tikz]{standalone}",
            "",
            "\\usepackage{amsmath} % for \\dfrac",
            "\\usepackage{tikz}",
            "\\tikzset{>=latex} % for LaTeX arrow head",
            "",
            "\\begin{document}",
            "",
            "% TIMELINE - particle physics",
            "% sources: http://web.ihep.su/dbserv/compas/src/",
            "%          http://www.particleadventure.org/other/history/",
            "%          https://en.wikipedia.org/wiki/Timeline_of_particle_discoveries",
            "\\large",
            "\\begin{tikzpicture}[] %[minimum height=10pt, text height=10pt,text depth=10pt,",
            "",
            "  % limits",
            "  \\newcount\\yearOne; \\yearOne=1900",
            "  \\newcount\\yoffset;",
            "  \\def\\w{18}       % width of axes",
            "  \\def\\n{4}        % number of decades",
            "  \\def\\lt{0.40}    %  ten tick length",
            "  \\def\\lf{0.36}    % five tick length",
            "  \\def\\lo{0.30}    %  one tick length",
            "  \\def\\lext{0.07}  % left extension of axes",
            "  \\def\\rext{1.045} % left extension of axes",
            "  ",
            "  % help functions",
            "  \\def\\yearLabel(#1,#2,#3){\\node[above,black!60!blue] at ({(#1-\\yearOne)*\\w/\\n/10},{\\lt*#2}) {#3};}",
            "  \\def\\yearArrowLabel(#1,#2,#3,#4){",
            "    \\def\\xy{{(#1-\\yearOne)*\\w/\\n/10}}; \\pgfmathparse{int(#2*100)};",
            "    \\ifnum \\pgfmathresult<0 % below",
            "      \\def\\yyp{{(\\lt*(0.90+#2))}}; \\def\\yyw{{(\\yyp-\\lt*#3)}}",
            "      \\draw[<-,thick,black!50!blue,align=center]",
            "        (\\xy,\\yyp) -- (\\xy,\\yyw)",
            "        node[below,black!80!blue] at (\\xy,\\yyw) {\\strut #4};",
            "    \\else % under",
            "      \\def\\yyp{{(\\lt*(0.10+#2)}}; \\def\\yyw{{(\\yyp+\\lt*#3)}}",
            "      \\draw[<-,thick,black!60!blue,align=center]",
            "        (\\xy,\\yyp) -- (\\xy,\\yyw)",
            "        node[above] at (\\xy,\\yyw) {#4};",
            "    \\fi}",
            "  \\def\\yearArrowLabelRed(#1,#2,#3,#4){",
            "    \\def\\xy{{(#1-\\yearOne)*\\w/\\n/10}}; \\pgfmathparse{int(#2*100)};",
            "      \\def\\yyp{{(\\lt*(0.90+#2))}}; \\def\\yyw{{(\\yyp-\\lt*#3)}}",
            "      \\fill[red,radius=2pt] (\\xy,0) circle;",
            "      \\draw[<-,thick,black!25!red,align=center]",
            "        (\\xy,\\yyp) -- (\\xy,\\yyw)",
            "        node[below,black!40!red] at (\\xy,\\yyw) {\\strut #4};",
            "     }  ",
            "  ",
            "  ",
            "  %---------------%",
            "  %  1900 - 1940  %",
            "  %---------------%",
            "  ",
            "  % axis",
            "  \\draw[thick] (-\\w*0.07,0) -- (\\w*\\rext,0);",
            "  ",
            "  % ticks",
            "  \\foreach \\tick in {0,1,...,\\n}{",
            "    \\def\\x{{\\tick*\\w/\\n}}",
            "    \\def\\year{\\the\\numexpr \\yearOne+\\tick*10 \\relax}",
            "    \\draw[thick] (\\x,-\\lt) -- (\\x,\\lt) % ten tick",
            "                 node[above] {\\year};",
            "\t",
            "\t\\ifnum \\tick<\\n",
            "      \\draw[thick] ({(\\x+\\w/\\n/2)},0) -- ({(\\x+\\w/\\n/2)},\\lf); % five tick",
            "      \\foreach \\ticko in {1,2,3,4,6,7,8,9}{",
            "        \\def\\xo{{(\\x+\\ticko*\\w/\\n/10)}}",
            "  \t    \\draw[thick] (\\xo,0) -- (\\xo,\\lo);  % one tick",
            "\t}\\fi",
            "  }",
            "  ",
            "  % extra ticks",
            "  \\draw[thick] (-1*\\w/\\n/10,0) -- (-1*\\w/\\n/10,\\lo);",
            "  \\draw[thick] (-2*\\w/\\n/10,0) -- (-2*\\w/\\n/10,\\lo);",
            "  \\draw[thick] ({\\w+\\w/\\n/10},0) -- ({\\w+\\w/\\n/10},\\lo);",
            "  ",
            "  % labels",
            "  \\yearArrowLabel(1897.83,-1.2,1.5,",
            "                  $\\text{e}^-$)      % electron 10/1897 Thomson",
            "  \\yearArrowLabel(1905.25,-1.2,1.5,",
            "                  $\\gamma$)          % photon   03/1905 Einstein",
            "  \\yearArrowLabel(1913.17, 1.2,1.5,",
            "                  atom nucleus)      % nucleus  02/1913 Rutherford",
            "  \\yearArrowLabel(1917.50,-1.2,1.5,",
            "                  $\\text{p}^+$)      % proton      1917 Rutherford (Philos. Mag., Ser. 6, Vol. 37, 581 (1919))",
            "  \\yearArrowLabel(1932.50, 1.2,1.5,",
            "                  anti-matter)       % anti-matter",
            "  \\yearArrowLabel(1932.50,-1.2,1.5,",
            "                  $\\text{e}^+$\\\\     % positron    1932 Anderson",
            "                  $\\text{n}^0$)      % neutron     1932 Chadwick",
            "  \\yearArrowLabel(1936.50,-1.2,1.5,",
            "                  $\\mu^\\pm$)         % muon        1936",
            "  ",
            "  ",
            "  %---------------%",
            "  %  1940 - 1980  %",
            "  %---------------%",
            "  ",
            "  \\yearOne=1940; \\advance\\yoffset by 120",
            "  \\begin{scope}[yshift=-\\yoffset]",
            "    ",
            "    % axis",
            "    \\draw[thick] (-\\w*\\lext,0) -- (\\w*\\rext,0);",
            "    ",
            "    % ticks",
            "    \\foreach \\tick in {0,1,...,\\n}{",
            "      \\def\\x{{\\tick*\\w/\\n}}",
            "      \\def\\year{\\the\\numexpr \\yearOne+\\tick*10 \\relax}",
            "      \\draw[thick] (\\x,-\\lt) -- (\\x,\\lt) % ten tick",
            "\t               node[above] {\\year};",
            "      \\ifnum \\tick<\\n",
            "        \\draw[thick] ({(\\x+\\w/\\n/2)},0) -- ({(\\x+\\w/\\n/2)},\\lf); % five tick",
            "        \\foreach \\ticko in {1,2,3,4,6,7,8,9}{",
            "          \\def\\xo{{(\\x+\\ticko*\\w/\\n/10)}}",
            "  \t      \\draw[thick] (\\xo,0) -- (\\xo,\\lo);  % one tick",
            "\t  }\\fi",
            "    }",
            "",
            "    % extra ticks",
            "    \\draw[thick] (-1*\\w/\\n/10,0) -- (-1*\\w/\\n/10,\\lo);",
            "    \\draw[thick] (-2*\\w/\\n/10,0) -- (-2*\\w/\\n/10,\\lo);",
            "    \\draw[thick] ({\\w+\\w/\\n/10},0) -- ({\\w+\\w/\\n/10},\\lo);",
            "  ",
            "    % labels",
            "    \\yearArrowLabel(1947.42,-1.2,1.5,",
            "                    $\\pi^\\pm$\\\\            % pions    05/1947 Lattes, Muirhead, Occhialini, Powell",
            "                    $\\text{K}^0$)          % neutral kaons 12/1947 Rochester & Butler, Nature, 160, 855",
            "    \\yearArrowLabel(1949.00,-1.2,1.5,",
            "                    $\\text{K}^\\pm$)        % kaons    12/1949 Powell, Fowler, Perkins, Nature, 163, 82",
            "    \\yearArrowLabel(1950.10,-2.2,1.8,",
            "                  \\,$\\pi^0$)               % pi0      01/1950 Caltech",
            "    \\yearArrowLabel(1952.00,-1.2,1.5,",
            "                    $\\Lambda^0$\\\\          % Lambda0  12/1950 Hopper, Biswas, Phys. Rev. 80, 1099",
            "                    $\\Delta$)              % 1952 Anderson, Fermi, (Chicago Cyclotron), Phys. Rev., 85, 936",
            "                                           % 1956 Ashkin (Rochester cyclotron), Phys. Rev., 101, 1149",
            "     % Sigma+ 1953 Bonetti, Nuovo Cimento, 10, 1; Danysz, Pniewski, Phil. Mag., 44, 348; Cosmotron Brookhaven, Phys. Rev., 93, 109",
            "     % Xi- \"negative hyperon\" 1954 Cowan (Caltech), Phys. Rev., 94, 161",
            "    \\yearArrowLabel(1953.20,-1.2,1.5,\\,\\,$\\Sigma^\\pm$\\\\\\,\\,$\\Xi^-$)",
            "    \\yearArrowLabel(1955.92,-1.2,1.5,$\\overline{\\text{p}}$\\,) % 11/1955 Chamberlain, Segrè (Bevatron) Phys. Rev. 100, 947",
            "    \\yearArrowLabel(1956.75,-1.2,1.5,$\\nu_\\text{e}$\\\\$\\overline{\\text{n}}$) % 09/1956 Reines, Cowan, Nature, 178, 446",
            "    \\yearArrowLabel(1957.80,-1.2,1.5,$\\Sigma^0$) % ",
            "    \\yearArrowLabel(1959.00,-1.2,1.5,$\\Xi^0$) % Xi 1959 (1964 Brookhaven)",
            "    % 1960  Sigma*(1385) Phys. Rev. Lett., 5, 520",
            "    \\yearArrowLabel(1961.20,-1.2,1.5,",
            "                    $\\rho$\\\\            % 1961 Erwin (Cosmotron) Phys. Rev. Lett., 6, 628",
            "                    $\\omega$\\\\          % 1961 Maglic, Alvarez, Phys. Rev. Lett., 7, 178",
            "                    $\\eta$\\\\            % 1961 Pevsner, Phys. Rev. Lett., 7, 421",
            "                    $\\text{K}^*$)       % 1961 Alston, Phys. Rev. Lett., 6, 300, 1962 Phys. Rev. Lett., 9, 330",
            "    % 19.. strangeness \"associated-production\", Pais",
            "    % 1962 Eightfold Way, Gell-Man",
            "    \\yearArrowLabel(1962.58,-1.2,1.5,\\vspace{2pt}",
            "                    $\\nu_\\mu$\\\\         % 07/1962, Ledderman, Danby, Phys. Rev. Lett. 9, 36",
            "                    $\\phi$)             % 1962, Pjerrou Phys. Rev. Lett., 9, 114, Bertanza, Phys. Rev. Lett., 9, 180",
            "    % 1962 f particle?",
            "    \\yearArrowLabel(1964.10,-1.2,1.5,",
            "                    $\\alpha_2$\\\\        %",
            "                    \\,$\\eta^*$\\\\        %",
            "                    \\,\\,$\\Omega^-$)     % 02/1964, Barnes, Brookhaven, Phys. Rev. Lett. 12, 204",
            "    \\yearArrowLabel(1964.50, 1.2,1.2,",
            "                    quark model\\\\",
            "                    \\small{up, down, strange}) % Gell-Mann",
            "    % 1967 Steven Weinberg, Abdus Salam: electroweak unification",
            "    \\yearArrowLabel(1974.50, 1.2,1.2,",
            "                    \\qquad\\qquad Standard Model\\\\",
            "                    \\small{charm})     % charm",
            "    % 1974 November Revolution",
            "    \\yearArrowLabel(1974.50,-1.2,1.5,$\\text{J/}\\Psi$\\,\\,\\\\$\\Psi'$\\\\\\,$\\Psi''$) % ",
            "    %\\yearLabel(1973,4.0,Standard Model) % Standard Model",
            "    % tau 1975 Perl, Abrams, Phys. Rev. Lett. 35, 1489",
            "    \\yearArrowLabel(1976.00,-1.2,1.5,$\\tau$\\\\$\\chi_\\text{c}$) % ",
            "    \\yearArrowLabel(1976.90,-1.2,1.5,",
            "                    $\\text{D}$        ) % 1976 SLAC",
            "    \\yearArrowLabel(1977.75, 1.2,1.2,",
            "                    \\small{bottom} )    % bottom",
            "    \\yearArrowLabel(1977.75,-1.2,1.5,$\\Upsilon$\\\\\\,$\\Upsilon'$\\\\\\,\\,$\\Upsilon''$\\\\\\small\\ldots) % Fermilab",
            "    \\yearArrowLabel(1979.65,-1.2,1.5,$\\Lambda_\\text{c}$\\\\$\\Sigma_\\text{c}$) % ",
            "    ",
            "  \\end{scope}",
            "  ",
            "  ",
            "  %---------------%",
            "  %  1980 - 2020  %",
            "  %---------------%",
            "  ",
            "  \\yearOne=1980; \\advance\\yoffset by 130",
            "  \\begin{scope}[yshift=-\\yoffset]",
            "    ",
            "    % axis",
            "    \\draw[->,thick] (-\\w*\\lext,0) -- (\\w*1.06,0);",
            "    ",
            "    % ticks",
            "    \\foreach \\tick in {0,1,...,\\n}{",
            "      \\def\\x{{\\tick*\\w/\\n}}",
            "      \\def\\year{\\the\\numexpr \\yearOne+\\tick*10 \\relax}",
            "      \\draw[thick] (\\x,-\\lt) -- (\\x,\\lt) % ten tick",
            "\t               node[above] {\\year};",
            "      \\ifnum \\tick<\\n",
            "        \\draw[thick] ({(\\x+\\w/\\n/2)},0) -- ({(\\x+\\w/\\n/2)},\\lf); % five tick",
            "        \\foreach \\ticko in {1,2,3,4,6,7,8,9}{",
            "          \\def\\xo{{(\\x+\\ticko*\\w/\\n/10)}}",
            "  \t      \\draw[thick] (\\xo,0) -- (\\xo,\\lo);  % one tick",
            "\t  }\\fi",
            "    }",
            "    ",
            "    % extra ticks",
            "    \\draw[thick] (-1*\\w/\\n/10,0) -- (-1*\\w/\\n/10,\\lo);",
            "    \\draw[thick] (-2*\\w/\\n/10,0) -- (-2*\\w/\\n/10,\\lo);",
            "    \\draw[thick] ({\\w+\\w/\\n/10},0) -- ({\\w+\\w/\\n/10},\\lo);",
            "  ",
            "    % labels",
            "    \\yearArrowLabel(1980.40,-1.2,1.5,",
            "                    $\\eta_\\text{c}$   )  % ",
            "    \\yearArrowLabel(1981.30,-1.2,1.5,",
            "                    B                 )  % ",
            "    \\yearArrowLabel(1983.05,-1.2,1.5,",
            "              \\mbox{$\\text{W}^\\pm$\\hspace{4pt}}\\\\",
            "                    $\\text{D}_\\text{s}$\\\\",
            "                    $\\Xi_\\text{c}$    )  % ",
            "    \\yearArrowLabel(1984.00,-1.2,1.5,",
            "              \\mbox{\\hspace{12pt}$\\text{Z}^0$} ) % ",
            "    \\yearArrowLabel(1991.60,-1.2,1.5,$\\text{B}_\\text{s}$\\\\$\\Lambda_\\text{b}$)  % Bs Fermilab",
            "    \\yearArrowLabel(1995.30,-1.2,1.5,t)  % ",
            "    \\yearArrowLabel(1995.30, 1.2,1.2,",
            "                    \\small{top}      )   %  ",
            "    \\yearArrowLabel(2000.60,-1.2,1.5,$\\nu_\\tau$)  % ",
            "    \\yearArrowLabel(2012.50,-1.2,1.5,H)  % ",
            "    %\\yearArrowLabelRed(2017.7,-1.2,1.5,X\\\\\\,$\\text{B}'$) % low mass",
            "    \\yearArrowLabelRed(2020.9,-1.2,1.5,LQ) % leptoquark",
            "    ",
            "  \\end{scope}",
            "  ",
            "\\end{tikzpicture}",
            "",
            "\\end{document}",
        ]),
    },
    {
        diagramType: "tikz",
        default: false,
        description: "MindMaps",
        title: "TikZ",
        keywords: ["TeX", "LaTex", "MindMaps", "Trees"],
        source: lines([
            "% Find more inspiring examples at: https://tikz.net/",
            "",
            "\\usepackage{tikz}",
            "\\usetikzlibrary{mindmap}",
            "\\pagestyle{empty}",
            "\\begin{document}",
            "",
            "\\begin{tikzpicture}[",
            "    mindmap, ",
            "    grow cyclic, ",
            "    every node/.style=concept, ",
            "    concept color=black!50,",
            "\tlevel 1/.append style={level distance=50mm,sibling angle=360/5},",
            "\tlevel 2/.append style={level distance=28mm,sibling angle=360/9},",
            "]",
            "",
            "\\definecolor{c1}{RGB}{77,117,179}",
            "\\definecolor{c2}{RGB}{158,77,179}",
            "\\definecolor{c3}{RGB}{179,77,77}",
            "\\definecolor{c4}{RGB}{158,179,77}",
            "\\definecolor{c5}{RGB}{77,179,117}",
            "",
            "\\definecolor{c3_3}{RGB}{217,38,38}",
            "\\definecolor{c3_4}{RGB}{217,80,38}",
            "\\definecolor{c3_5}{RGB}{217,122,38}",
            "\\definecolor{c4_1}{RGB}{217,166,38}",
            "\\definecolor{c4_2}{RGB}{217,208,38}",
            "\\definecolor{c4_3}{RGB}{181,217,38}",
            "\\definecolor{c4_4}{RGB}{139,217,38}",
            "\\definecolor{c4_5}{RGB}{98,217,38}",
            "\\definecolor{c5_1}{RGB}{53,217,38}",
            "\\definecolor{c5_2}{RGB}{38,217,65}",
            "\\definecolor{c5_3}{RGB}{38,217,110}",
            "\\definecolor{c5_4}{RGB}{38,217,151}",
            "\\definecolor{c5_5}{RGB}{38,217,193}",
            "\\definecolor{c1_1}{RGB}{38,196,217}",
            "\\definecolor{c1_2}{RGB}{38,154,217}",
            "\\definecolor{c1_3}{RGB}{38,110,217}",
            "\\definecolor{c1_4}{RGB}{38,68,217}",
            "\\definecolor{c1_5}{RGB}{50,38,217}",
            "\\definecolor{c2_1}{RGB}{95,38,217}",
            "\\definecolor{c2_2}{RGB}{136,38,217}",
            "\\definecolor{c2_3}{RGB}{181,38,217}",
            "\\definecolor{c2_4}{RGB}{217,38,211}",
            "\\definecolor{c2_5}{RGB}{217,38,169}",
            "\\definecolor{c3_1}{RGB}{217,38,125}",
            "\\definecolor{c3_2}{RGB}{217,38,83}",
            "",
            "\\node",
            "{\\Huge{Main idea}}",
            "child [concept color=c1] { ",
            "    node {\\Large{First part}}",
            "\tchild [concept color=c1_1] { node {Item} }",
            "\tchild [concept color=c1_2] { node {Other item} }",
            "\tchild [concept color=c1_3] { node {Yet another item} }",
            "\tchild [concept color=c1_4] { node {Item} }",
            "\tchild [concept color=c1_5] { node {Item} }",
            "}",
            "child [concept color=c2] { ",
            "    node {\\Large{Second part}}",
            "\tchild [concept color=c2_1] { node {Item} }",
            "\tchild [concept color=c2_2] { node {Other item} }",
            "\tchild [concept color=c2_3] { node {Yet another item} }",
            "\tchild [concept color=c2_4] { node {Item} }",
            "\tchild [concept color=c2_5] { node {Item} }",
            "}",
            "child [concept color=c3] { ",
            "    node {\\Large{Third part}}",
            "\tchild [concept color=c3_1] { node {Item} }",
            "\tchild [concept color=c3_2] { node {Other item} }",
            "\tchild [concept color=c3_3] { node {Yet another item} }",
            "\tchild [concept color=c3_4] { node {Item} }",
            "\tchild [concept color=c3_5] { node {Item} }",
            "}",
            "child [concept color=c4] { ",
            "    node {\\Large{Fourth part}}",
            "\tchild [concept color=c4_1] { node {Item} }",
            "\tchild [concept color=c4_2] { node {Other item} }",
            "\tchild [concept color=c4_3] { node {Yet another item} }",
            "\tchild [concept color=c4_4] { node {Item} }",
            "\tchild [concept color=c4_5] { node {Item} }",
            "}",
            "child [concept color=c5] { ",
            "    node {\\Large{Fifth part}}",
            "\tchild [concept color=c5_1] { node {Item} }",
            "\tchild [concept color=c5_2] { node {Other item} }",
            "\tchild [concept color=c5_3] { node {Yet another item} }",
            "\tchild [concept color=c5_4] { node {Item} }",
            "\tchild [concept color=c5_5] { node {Item} }",
            "};",
            "",
            "\\end{tikzpicture}",
            "\\end{document}",
        ]),
    },
]);

export default tikz;
