import { defineExamples, lines } from '../define';

const vegalite = defineExamples([
    {
        diagramType: "vegalite",
        default: true,
        description: "Default",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        language: "json",
        keywords: ["chart", "dataviz", "scales"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v4.json\",",
            "  \"description\": \"Horizontally concatenated charts that show different types of discretizing scales.\",",
            "  \"data\": {",
            "    \"values\": [",
            "      {\"a\": \"A\", \"b\": 28},",
            "      {\"a\": \"B\", \"b\": 55},",
            "      {\"a\": \"C\", \"b\": 43},",
            "      {\"a\": \"D\", \"b\": 91},",
            "      {\"a\": \"E\", \"b\": 81},",
            "      {\"a\": \"F\", \"b\": 53},",
            "      {\"a\": \"G\", \"b\": 19},",
            "      {\"a\": \"H\", \"b\": 87},",
            "      {\"a\": \"I\", \"b\": 52}",
            "    ]",
            "  },",
            "  \"hconcat\": [",
            "    {",
            "      \"mark\": \"circle\",",
            "      \"encoding\": {",
            "        \"y\": {",
            "          \"field\": \"b\",",
            "          \"type\": \"nominal\",",
            "          \"sort\": null,",
            "          \"axis\": {",
            "            \"ticks\": false,",
            "            \"domain\": false,",
            "            \"title\": null",
            "          }",
            "        },",
            "        \"size\": {",
            "          \"field\": \"b\",",
            "          \"type\": \"quantitative\",",
            "          \"scale\": {",
            "            \"type\": \"quantize\"",
            "          }",
            "        },",
            "        \"color\": {",
            "          \"field\": \"b\",",
            "          \"type\": \"quantitative\",",
            "          \"scale\": {",
            "            \"type\": \"quantize\",",
            "            \"zero\": true",
            "          },",
            "          \"legend\": {",
            "            \"title\": \"Quantize\"",
            "          }",
            "        }",
            "      }",
            "    },",
            "    {",
            "      \"mark\": \"circle\",",
            "      \"encoding\": {",
            "        \"y\": {",
            "          \"field\": \"b\",",
            "          \"type\": \"nominal\",",
            "          \"sort\": null,",
            "          \"axis\": {",
            "            \"ticks\": false,",
            "            \"domain\": false,",
            "            \"title\": null",
            "          }",
            "        },",
            "        \"size\": {",
            "          \"field\": \"b\",",
            "          \"type\": \"quantitative\",",
            "          \"scale\": {",
            "            \"type\": \"quantile\",",
            "            \"range\": [80, 160, 240, 320, 400]",
            "          }",
            "        },",
            "        \"color\": {",
            "          \"field\": \"b\",",
            "          \"type\": \"quantitative\",",
            "          \"scale\": {",
            "            \"type\": \"quantile\",",
            "            \"scheme\": \"magma\"",
            "          },",
            "          \"legend\": {",
            "            \"format\": \"d\",",
            "            \"title\": \"Quantile\"",
            "          }",
            "        }",
            "      }",
            "    },",
            "    {",
            "      \"mark\": \"circle\",",
            "      \"encoding\": {",
            "        \"y\": {",
            "          \"field\": \"b\",",
            "          \"type\": \"nominal\",",
            "          \"sort\": null,",
            "          \"axis\": {",
            "            \"ticks\": false,",
            "            \"domain\": false,",
            "            \"title\": null",
            "          }",
            "        },",
            "        \"size\": {",
            "          \"field\": \"b\",",
            "          \"type\": \"quantitative\",",
            "          \"scale\": {",
            "            \"type\": \"threshold\",",
            "            \"domain\": [30, 70],",
            "            \"range\": [80, 200, 320]",
            "          }",
            "        },",
            "        \"color\": {",
            "          \"field\": \"b\",",
            "          \"type\": \"quantitative\",",
            "          \"scale\": {",
            "            \"type\": \"threshold\",",
            "            \"domain\": [30, 70],",
            "            \"scheme\": \"viridis\"",
            "          },",
            "          \"legend\": {",
            "            \"title\": \"Threshold\"",
            "          }",
            "        }",
            "      }",
            "    }",
            "  ],",
            "  \"resolve\": {",
            "    \"scale\": {",
            "      \"color\": \"independent\",",
            "      \"size\": \"independent\"",
            "    }",
            "  }",
            "}",
            "",
        ], true),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Aggregate Bar Chart",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "bar"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"description\": \"A bar chart showing the US population distribution of age groups in 2000.\",",
            "  \"height\": {\"step\": 17},",
            "  \"data\": { ",
            "    \"values\": [",
            "      {\"year\":1990,\"age\":0,\"sex\":1,\"people\":9307465},",
            "      {\"year\":1990,\"age\":0,\"sex\":2,\"people\":8894007},",
            "      {\"year\":1990,\"age\":5,\"sex\":1,\"people\":9274732},",
            "      {\"year\":1990,\"age\":5,\"sex\":2,\"people\":8799955},",
            "      {\"year\":1990,\"age\":10,\"sex\":1,\"people\":8782542},",
            "      {\"year\":1990,\"age\":10,\"sex\":2,\"people\":8337284},",
            "      {\"year\":1990,\"age\":15,\"sex\":1,\"people\":9020572},",
            "      {\"year\":1990,\"age\":15,\"sex\":2,\"people\":8590991},",
            "      {\"year\":1990,\"age\":20,\"sex\":1,\"people\":9436188},",
            "      {\"year\":1990,\"age\":20,\"sex\":2,\"people\":9152644},",
            "      {\"year\":1990,\"age\":25,\"sex\":1,\"people\":10658027},",
            "      {\"year\":1990,\"age\":25,\"sex\":2,\"people\":10587292},",
            "      {\"year\":1990,\"age\":30,\"sex\":1,\"people\":11028712},",
            "      {\"year\":1990,\"age\":30,\"sex\":2,\"people\":11105750},",
            "      {\"year\":1990,\"age\":35,\"sex\":1,\"people\":9853933},",
            "      {\"year\":1990,\"age\":35,\"sex\":2,\"people\":10038644},",
            "      {\"year\":1990,\"age\":40,\"sex\":1,\"people\":8712632},",
            "      {\"year\":1990,\"age\":40,\"sex\":2,\"people\":8928252},",
            "      {\"year\":1990,\"age\":45,\"sex\":1,\"people\":6848082},",
            "      {\"year\":1990,\"age\":45,\"sex\":2,\"people\":7115129},",
            "      {\"year\":1990,\"age\":50,\"sex\":1,\"people\":5553992},",
            "      {\"year\":1990,\"age\":50,\"sex\":2,\"people\":5899925},",
            "      {\"year\":1990,\"age\":55,\"sex\":1,\"people\":4981670},",
            "      {\"year\":1990,\"age\":55,\"sex\":2,\"people\":5460506},",
            "      {\"year\":1990,\"age\":60,\"sex\":1,\"people\":4953822},",
            "      {\"year\":1990,\"age\":60,\"sex\":2,\"people\":5663205},",
            "      {\"year\":1990,\"age\":65,\"sex\":1,\"people\":4538398},",
            "      {\"year\":1990,\"age\":65,\"sex\":2,\"people\":5594108},",
            "      {\"year\":1990,\"age\":70,\"sex\":1,\"people\":3429420},",
            "      {\"year\":1990,\"age\":70,\"sex\":2,\"people\":4610222},",
            "      {\"year\":1990,\"age\":75,\"sex\":1,\"people\":2344932},",
            "      {\"year\":1990,\"age\":75,\"sex\":2,\"people\":3723980},",
            "      {\"year\":1990,\"age\":80,\"sex\":1,\"people\":1342996},",
            "      {\"year\":1990,\"age\":80,\"sex\":2,\"people\":2545730},",
            "      {\"year\":1990,\"age\":85,\"sex\":1,\"people\":588790},",
            "      {\"year\":1990,\"age\":85,\"sex\":2,\"people\":1419494},",
            "      {\"year\":1990,\"age\":90,\"sex\":1,\"people\":238459},",
            "      {\"year\":1990,\"age\":90,\"sex\":2,\"people\":745146},",
            "      {\"year\":2000,\"age\":0,\"sex\":1,\"people\":9735380},",
            "      {\"year\":2000,\"age\":0,\"sex\":2,\"people\":9310714},",
            "      {\"year\":2000,\"age\":5,\"sex\":1,\"people\":10552146},",
            "      {\"year\":2000,\"age\":5,\"sex\":2,\"people\":10069564},",
            "      {\"year\":2000,\"age\":10,\"sex\":1,\"people\":10563233},",
            "      {\"year\":2000,\"age\":10,\"sex\":2,\"people\":10022524},",
            "      {\"year\":2000,\"age\":15,\"sex\":1,\"people\":10237419},",
            "      {\"year\":2000,\"age\":15,\"sex\":2,\"people\":9692669},",
            "      {\"year\":2000,\"age\":20,\"sex\":1,\"people\":9731315},",
            "      {\"year\":2000,\"age\":20,\"sex\":2,\"people\":9324244},",
            "      {\"year\":2000,\"age\":25,\"sex\":1,\"people\":9659493},",
            "      {\"year\":2000,\"age\":25,\"sex\":2,\"people\":9518507},",
            "      {\"year\":2000,\"age\":30,\"sex\":1,\"people\":10205879},",
            "      {\"year\":2000,\"age\":30,\"sex\":2,\"people\":10119296},",
            "      {\"year\":2000,\"age\":35,\"sex\":1,\"people\":11475182},",
            "      {\"year\":2000,\"age\":35,\"sex\":2,\"people\":11635647},",
            "      {\"year\":2000,\"age\":40,\"sex\":1,\"people\":11320252},",
            "      {\"year\":2000,\"age\":40,\"sex\":2,\"people\":11488578},",
            "      {\"year\":2000,\"age\":45,\"sex\":1,\"people\":9925006},",
            "      {\"year\":2000,\"age\":45,\"sex\":2,\"people\":10261253},",
            "      {\"year\":2000,\"age\":50,\"sex\":1,\"people\":8507934},",
            "      {\"year\":2000,\"age\":50,\"sex\":2,\"people\":8911133},",
            "      {\"year\":2000,\"age\":55,\"sex\":1,\"people\":6459082},",
            "      {\"year\":2000,\"age\":55,\"sex\":2,\"people\":6921268},",
            "      {\"year\":2000,\"age\":60,\"sex\":1,\"people\":5123399},",
            "      {\"year\":2000,\"age\":60,\"sex\":2,\"people\":5668961},",
            "      {\"year\":2000,\"age\":65,\"sex\":1,\"people\":4453623},",
            "      {\"year\":2000,\"age\":65,\"sex\":2,\"people\":4804784},",
            "      {\"year\":2000,\"age\":70,\"sex\":1,\"people\":3792145},",
            "      {\"year\":2000,\"age\":70,\"sex\":2,\"people\":5184855},",
            "      {\"year\":2000,\"age\":75,\"sex\":1,\"people\":2912655},",
            "      {\"year\":2000,\"age\":75,\"sex\":2,\"people\":4355644},",
            "      {\"year\":2000,\"age\":80,\"sex\":1,\"people\":1902638},",
            "      {\"year\":2000,\"age\":80,\"sex\":2,\"people\":3221898},",
            "      {\"year\":2000,\"age\":85,\"sex\":1,\"people\":970357},",
            "      {\"year\":2000,\"age\":85,\"sex\":2,\"people\":1981156},",
            "      {\"year\":2000,\"age\":90,\"sex\":1,\"people\":336303},",
            "      {\"year\":2000,\"age\":90,\"sex\":2,\"people\":1064581}",
            "    ]",
            "  },",
            "  \"transform\": [{\"filter\": \"datum.year == 2000\"}],",
            "  \"mark\": \"bar\",",
            "  \"encoding\": {",
            "    \"x\": {",
            "        \"field\": \"age\"",
            "    },",
            "    \"y\": {",
            "      \"aggregate\": \"sum\", ",
            "      \"field\": \"people\",",
            "      \"title\": \"population\"",
            "    }",
            "  }",
            "}",
        ]),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Diverging Stacked Bar Chart (Population Pyramid)",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "bar", "pyramid"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"description\": \"A population pyramid for the US in 2000, created using stack. See https://vega.github.io/vega-lite/examples/concat_population_pyramid.html for a variant of this created using concat.\",  \"height\": {\"step\": 17},",
            "  \"data\": { ",
            "      \"values\": [",
            "        {\"year\":1990,\"age\":0,\"sex\":1,\"people\":9307465},",
            "        {\"year\":1990,\"age\":0,\"sex\":2,\"people\":8894007},",
            "        {\"year\":1990,\"age\":5,\"sex\":1,\"people\":9274732},",
            "        {\"year\":1990,\"age\":5,\"sex\":2,\"people\":8799955},",
            "        {\"year\":1990,\"age\":10,\"sex\":1,\"people\":8782542},",
            "        {\"year\":1990,\"age\":10,\"sex\":2,\"people\":8337284},",
            "        {\"year\":1990,\"age\":15,\"sex\":1,\"people\":9020572},",
            "        {\"year\":1990,\"age\":15,\"sex\":2,\"people\":8590991},",
            "        {\"year\":1990,\"age\":20,\"sex\":1,\"people\":9436188},",
            "        {\"year\":1990,\"age\":20,\"sex\":2,\"people\":9152644},",
            "        {\"year\":1990,\"age\":25,\"sex\":1,\"people\":10658027},",
            "        {\"year\":1990,\"age\":25,\"sex\":2,\"people\":10587292},",
            "        {\"year\":1990,\"age\":30,\"sex\":1,\"people\":11028712},",
            "        {\"year\":1990,\"age\":30,\"sex\":2,\"people\":11105750},",
            "        {\"year\":1990,\"age\":35,\"sex\":1,\"people\":9853933},",
            "        {\"year\":1990,\"age\":35,\"sex\":2,\"people\":10038644},",
            "        {\"year\":1990,\"age\":40,\"sex\":1,\"people\":8712632},",
            "        {\"year\":1990,\"age\":40,\"sex\":2,\"people\":8928252},",
            "        {\"year\":1990,\"age\":45,\"sex\":1,\"people\":6848082},",
            "        {\"year\":1990,\"age\":45,\"sex\":2,\"people\":7115129},",
            "        {\"year\":1990,\"age\":50,\"sex\":1,\"people\":5553992},",
            "        {\"year\":1990,\"age\":50,\"sex\":2,\"people\":5899925},",
            "        {\"year\":1990,\"age\":55,\"sex\":1,\"people\":4981670},",
            "        {\"year\":1990,\"age\":55,\"sex\":2,\"people\":5460506},",
            "        {\"year\":1990,\"age\":60,\"sex\":1,\"people\":4953822},",
            "        {\"year\":1990,\"age\":60,\"sex\":2,\"people\":5663205},",
            "        {\"year\":1990,\"age\":65,\"sex\":1,\"people\":4538398},",
            "        {\"year\":1990,\"age\":65,\"sex\":2,\"people\":5594108},",
            "        {\"year\":1990,\"age\":70,\"sex\":1,\"people\":3429420},",
            "        {\"year\":1990,\"age\":70,\"sex\":2,\"people\":4610222},",
            "        {\"year\":1990,\"age\":75,\"sex\":1,\"people\":2344932},",
            "        {\"year\":1990,\"age\":75,\"sex\":2,\"people\":3723980},",
            "        {\"year\":1990,\"age\":80,\"sex\":1,\"people\":1342996},",
            "        {\"year\":1990,\"age\":80,\"sex\":2,\"people\":2545730},",
            "        {\"year\":1990,\"age\":85,\"sex\":1,\"people\":588790},",
            "        {\"year\":1990,\"age\":85,\"sex\":2,\"people\":1419494},",
            "        {\"year\":1990,\"age\":90,\"sex\":1,\"people\":238459},",
            "        {\"year\":1990,\"age\":90,\"sex\":2,\"people\":745146},",
            "        {\"year\":2000,\"age\":0,\"sex\":1,\"people\":9735380},",
            "        {\"year\":2000,\"age\":0,\"sex\":2,\"people\":9310714},",
            "        {\"year\":2000,\"age\":5,\"sex\":1,\"people\":10552146},",
            "        {\"year\":2000,\"age\":5,\"sex\":2,\"people\":10069564},",
            "        {\"year\":2000,\"age\":10,\"sex\":1,\"people\":10563233},",
            "        {\"year\":2000,\"age\":10,\"sex\":2,\"people\":10022524},",
            "        {\"year\":2000,\"age\":15,\"sex\":1,\"people\":10237419},",
            "        {\"year\":2000,\"age\":15,\"sex\":2,\"people\":9692669},",
            "        {\"year\":2000,\"age\":20,\"sex\":1,\"people\":9731315},",
            "        {\"year\":2000,\"age\":20,\"sex\":2,\"people\":9324244},",
            "        {\"year\":2000,\"age\":25,\"sex\":1,\"people\":9659493},",
            "        {\"year\":2000,\"age\":25,\"sex\":2,\"people\":9518507},",
            "        {\"year\":2000,\"age\":30,\"sex\":1,\"people\":10205879},",
            "        {\"year\":2000,\"age\":30,\"sex\":2,\"people\":10119296},",
            "        {\"year\":2000,\"age\":35,\"sex\":1,\"people\":11475182},",
            "        {\"year\":2000,\"age\":35,\"sex\":2,\"people\":11635647},",
            "        {\"year\":2000,\"age\":40,\"sex\":1,\"people\":11320252},",
            "        {\"year\":2000,\"age\":40,\"sex\":2,\"people\":11488578},",
            "        {\"year\":2000,\"age\":45,\"sex\":1,\"people\":9925006},",
            "        {\"year\":2000,\"age\":45,\"sex\":2,\"people\":10261253},",
            "        {\"year\":2000,\"age\":50,\"sex\":1,\"people\":8507934},",
            "        {\"year\":2000,\"age\":50,\"sex\":2,\"people\":8911133},",
            "        {\"year\":2000,\"age\":55,\"sex\":1,\"people\":6459082},",
            "        {\"year\":2000,\"age\":55,\"sex\":2,\"people\":6921268},",
            "        {\"year\":2000,\"age\":60,\"sex\":1,\"people\":5123399},",
            "        {\"year\":2000,\"age\":60,\"sex\":2,\"people\":5668961},",
            "        {\"year\":2000,\"age\":65,\"sex\":1,\"people\":4453623},",
            "        {\"year\":2000,\"age\":65,\"sex\":2,\"people\":4804784},",
            "        {\"year\":2000,\"age\":70,\"sex\":1,\"people\":3792145},",
            "        {\"year\":2000,\"age\":70,\"sex\":2,\"people\":5184855},",
            "        {\"year\":2000,\"age\":75,\"sex\":1,\"people\":2912655},",
            "        {\"year\":2000,\"age\":75,\"sex\":2,\"people\":4355644},",
            "        {\"year\":2000,\"age\":80,\"sex\":1,\"people\":1902638},",
            "        {\"year\":2000,\"age\":80,\"sex\":2,\"people\":3221898},",
            "        {\"year\":2000,\"age\":85,\"sex\":1,\"people\":970357},",
            "        {\"year\":2000,\"age\":85,\"sex\":2,\"people\":1981156},",
            "        {\"year\":2000,\"age\":90,\"sex\":1,\"people\":336303},",
            "        {\"year\":2000,\"age\":90,\"sex\":2,\"people\":1064581}",
            "      ]",
            "   },",
            "  \"transform\": [",
            "    {\"filter\": \"datum.year == 2000\"},",
            "    {\"calculate\": \"datum.sex == 2 ? 'Female' : 'Male'\", \"as\": \"gender\"},",
            "    {\"calculate\": \"datum.sex == 2 ? -datum.people : datum.people\", \"as\": \"signed_people\"}",
            "  ],",
            "  \"width\": 300,",
            "  \"height\": 200,",
            "  \"mark\": \"bar\",",
            "  \"encoding\": {",
            "    \"y\": {",
            "      \"field\": \"age\",",
            "      \"axis\": null, \"sort\": \"descending\"",
            "    },",
            "    \"x\": {",
            "      \"aggregate\": \"sum\", \"field\": \"signed_people\",",
            "      \"title\": \"population\",",
            "      \"axis\": {\"format\": \"s\"}",
            "    },",
            "    \"color\": {",
            "      \"field\": \"gender\",",
            "      \"scale\": {\"range\": [\"#675193\", \"#ca8861\"]},",
            "      \"legend\": {\"orient\": \"top\", \"title\": null}",
            "    }",
            "  },",
            "  \"config\": {",
            "    \"view\": {\"stroke\": null},",
            "    \"axis\": {\"grid\": false}",
            "  }",
            "}",
        ]),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Normalized Stacked Bar Chart",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "bar", "normalized", "stacked"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"data\": { ",
            "    \"values\": [",
            "      {\"year\":1990,\"age\":0,\"sex\":1,\"people\":9307465},",
            "      {\"year\":1990,\"age\":0,\"sex\":2,\"people\":8894007},",
            "      {\"year\":1990,\"age\":5,\"sex\":1,\"people\":9274732},",
            "      {\"year\":1990,\"age\":5,\"sex\":2,\"people\":8799955},",
            "      {\"year\":1990,\"age\":10,\"sex\":1,\"people\":8782542},",
            "      {\"year\":1990,\"age\":10,\"sex\":2,\"people\":8337284},",
            "      {\"year\":1990,\"age\":15,\"sex\":1,\"people\":9020572},",
            "      {\"year\":1990,\"age\":15,\"sex\":2,\"people\":8590991},",
            "      {\"year\":1990,\"age\":20,\"sex\":1,\"people\":9436188},",
            "      {\"year\":1990,\"age\":20,\"sex\":2,\"people\":9152644},",
            "      {\"year\":1990,\"age\":25,\"sex\":1,\"people\":10658027},",
            "      {\"year\":1990,\"age\":25,\"sex\":2,\"people\":10587292},",
            "      {\"year\":1990,\"age\":30,\"sex\":1,\"people\":11028712},",
            "      {\"year\":1990,\"age\":30,\"sex\":2,\"people\":11105750},",
            "      {\"year\":1990,\"age\":35,\"sex\":1,\"people\":9853933},",
            "      {\"year\":1990,\"age\":35,\"sex\":2,\"people\":10038644},",
            "      {\"year\":1990,\"age\":40,\"sex\":1,\"people\":8712632},",
            "      {\"year\":1990,\"age\":40,\"sex\":2,\"people\":8928252},",
            "      {\"year\":1990,\"age\":45,\"sex\":1,\"people\":6848082},",
            "      {\"year\":1990,\"age\":45,\"sex\":2,\"people\":7115129},",
            "      {\"year\":1990,\"age\":50,\"sex\":1,\"people\":5553992},",
            "      {\"year\":1990,\"age\":50,\"sex\":2,\"people\":5899925},",
            "      {\"year\":1990,\"age\":55,\"sex\":1,\"people\":4981670},",
            "      {\"year\":1990,\"age\":55,\"sex\":2,\"people\":5460506},",
            "      {\"year\":1990,\"age\":60,\"sex\":1,\"people\":4953822},",
            "      {\"year\":1990,\"age\":60,\"sex\":2,\"people\":5663205},",
            "      {\"year\":1990,\"age\":65,\"sex\":1,\"people\":4538398},",
            "      {\"year\":1990,\"age\":65,\"sex\":2,\"people\":5594108},",
            "      {\"year\":1990,\"age\":70,\"sex\":1,\"people\":3429420},",
            "      {\"year\":1990,\"age\":70,\"sex\":2,\"people\":4610222},",
            "      {\"year\":1990,\"age\":75,\"sex\":1,\"people\":2344932},",
            "      {\"year\":1990,\"age\":75,\"sex\":2,\"people\":3723980},",
            "      {\"year\":1990,\"age\":80,\"sex\":1,\"people\":1342996},",
            "      {\"year\":1990,\"age\":80,\"sex\":2,\"people\":2545730},",
            "      {\"year\":1990,\"age\":85,\"sex\":1,\"people\":588790},",
            "      {\"year\":1990,\"age\":85,\"sex\":2,\"people\":1419494},",
            "      {\"year\":1990,\"age\":90,\"sex\":1,\"people\":238459},",
            "      {\"year\":1990,\"age\":90,\"sex\":2,\"people\":745146},",
            "      {\"year\":2000,\"age\":0,\"sex\":1,\"people\":9735380},",
            "      {\"year\":2000,\"age\":0,\"sex\":2,\"people\":9310714},",
            "      {\"year\":2000,\"age\":5,\"sex\":1,\"people\":10552146},",
            "      {\"year\":2000,\"age\":5,\"sex\":2,\"people\":10069564},",
            "      {\"year\":2000,\"age\":10,\"sex\":1,\"people\":10563233},",
            "      {\"year\":2000,\"age\":10,\"sex\":2,\"people\":10022524},",
            "      {\"year\":2000,\"age\":15,\"sex\":1,\"people\":10237419},",
            "      {\"year\":2000,\"age\":15,\"sex\":2,\"people\":9692669},",
            "      {\"year\":2000,\"age\":20,\"sex\":1,\"people\":9731315},",
            "      {\"year\":2000,\"age\":20,\"sex\":2,\"people\":9324244},",
            "      {\"year\":2000,\"age\":25,\"sex\":1,\"people\":9659493},",
            "      {\"year\":2000,\"age\":25,\"sex\":2,\"people\":9518507},",
            "      {\"year\":2000,\"age\":30,\"sex\":1,\"people\":10205879},",
            "      {\"year\":2000,\"age\":30,\"sex\":2,\"people\":10119296},",
            "      {\"year\":2000,\"age\":35,\"sex\":1,\"people\":11475182},",
            "      {\"year\":2000,\"age\":35,\"sex\":2,\"people\":11635647},",
            "      {\"year\":2000,\"age\":40,\"sex\":1,\"people\":11320252},",
            "      {\"year\":2000,\"age\":40,\"sex\":2,\"people\":11488578},",
            "      {\"year\":2000,\"age\":45,\"sex\":1,\"people\":9925006},",
            "      {\"year\":2000,\"age\":45,\"sex\":2,\"people\":10261253},",
            "      {\"year\":2000,\"age\":50,\"sex\":1,\"people\":8507934},",
            "      {\"year\":2000,\"age\":50,\"sex\":2,\"people\":8911133},",
            "      {\"year\":2000,\"age\":55,\"sex\":1,\"people\":6459082},",
            "      {\"year\":2000,\"age\":55,\"sex\":2,\"people\":6921268},",
            "      {\"year\":2000,\"age\":60,\"sex\":1,\"people\":5123399},",
            "      {\"year\":2000,\"age\":60,\"sex\":2,\"people\":5668961},",
            "      {\"year\":2000,\"age\":65,\"sex\":1,\"people\":4453623},",
            "      {\"year\":2000,\"age\":65,\"sex\":2,\"people\":4804784},",
            "      {\"year\":2000,\"age\":70,\"sex\":1,\"people\":3792145},",
            "      {\"year\":2000,\"age\":70,\"sex\":2,\"people\":5184855},",
            "      {\"year\":2000,\"age\":75,\"sex\":1,\"people\":2912655},",
            "      {\"year\":2000,\"age\":75,\"sex\":2,\"people\":4355644},",
            "      {\"year\":2000,\"age\":80,\"sex\":1,\"people\":1902638},",
            "      {\"year\":2000,\"age\":80,\"sex\":2,\"people\":3221898},",
            "      {\"year\":2000,\"age\":85,\"sex\":1,\"people\":970357},",
            "      {\"year\":2000,\"age\":85,\"sex\":2,\"people\":1981156},",
            "      {\"year\":2000,\"age\":90,\"sex\":1,\"people\":336303},",
            "      {\"year\":2000,\"age\":90,\"sex\":2,\"people\":1064581}",
            "    ]",
            "  },",
            "  \"transform\": [",
            "    {\"filter\": \"datum.year == 2000\"},",
            "    {\"calculate\": \"datum.sex == 2 ? 'Female' : 'Male'\", \"as\": \"gender\"}",
            "  ],",
            "  \"height\": {\"step\": 17},",
            "  \"encoding\": {",
            "    \"y\": {\"field\": \"age\"}",
            "  },",
            "  \"layer\": [{",
            "    \"mark\": \"bar\",",
            "    \"encoding\": {",
            "      \"x\": {",
            "        \"aggregate\": \"sum\", \"field\": \"people\",",
            "        \"title\": \"population\",",
            "        \"stack\":  \"normalize\"",
            "      },",
            "      \"color\": {",
            "        \"field\": \"gender\",",
            "        \"scale\": {\"range\": [\"#675193\", \"#ca8861\"]}",
            "      }",
            "    }",
            "  }, {",
            "    \"mark\": {\"type\": \"text\", \"opacity\": 0.9, \"color\": \"white\"},",
            "    \"encoding\": {",
            "      \"x\": {",
            "        \"aggregate\": \"sum\", \"field\": \"people\",",
            "        \"title\": \"population\",",
            "        \"stack\":  \"normalize\",",
            "        \"bandPosition\": 0.5",
            "      },",
            "      \"text\": {",
            "        \"aggregate\": \"sum\", \"field\": \"people\",",
            "        \"title\": \"population\"",
            "      },",
            "      \"detail\": {",
            "        \"field\": \"gender\"",
            "      }",
            "    }",
            "  }]",
            "}",
        ]),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Simple Bar Chart with Labels and Emojis",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "bar", "emojis"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"description\": \"Vega-Lite version of bar chart from https://observablehq.com/@d3/learn-d3-scales.\",",
            "  \"width\": 400,",
            "  \"data\": {",
            "    \"values\": [",
            "      {\"name\": \"🍊\", \"count\": 21},",
            "      {\"name\": \"🍇\", \"count\": 13},",
            "      {\"name\": \"🍏\", \"count\": 8},",
            "      {\"name\": \"🍌\", \"count\": 5},",
            "      {\"name\": \"🍐\", \"count\": 3},",
            "      {\"name\": \"🍋\", \"count\": 2},",
            "      {\"name\": \"🍎\", \"count\": 1},",
            "      {\"name\": \"🍉\", \"count\": 1}",
            "    ]",
            "  },",
            "  \"encoding\": {",
            "    \"y\": {\"field\": \"name\", \"type\": \"nominal\", \"sort\": \"-x\", \"title\": null},",
            "    \"x\": {\"field\": \"count\", \"type\": \"quantitative\", \"title\": null}",
            "  },",
            "  \"layer\": [{",
            "    \"mark\": \"bar\",",
            "    \"encoding\": {",
            "      \"color\": {",
            "        \"field\": \"count\",",
            "        \"type\": \"quantitative\",",
            "        \"title\": \"Number of fruit\"",
            "      }",
            "    }",
            "  }, {",
            "    \"mark\": {",
            "      \"type\": \"text\",",
            "      \"align\": \"right\",",
            "      \"xOffset\": -4,",
            "      \"aria\": false",
            "    },",
            "    \"encoding\": {",
            "      \"text\": {\"field\": \"count\", \"type\": \"quantitative\"},",
            "      \"color\": {",
            "        \"condition\": {",
            "          \"test\": {\"field\": \"count\", \"gt\": 10},",
            "          \"value\": \"white\"",
            "        },",
            "        \"value\": \"black\"",
            "      }",
            "    }",
            "  }]",
            "}",
        ]),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Bump Chart",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "line"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"description\": \"Bump chart\",",
            "  \"data\": {",
            "    \"values\": [",
            "      {\"build\": 1, \"result\": \"PASSED\"},",
            "      {\"build\": 2, \"result\": \"PASSED\"},",
            "      {\"build\": 3, \"result\": \"FAILED\"},",
            "      {\"build\": 4, \"result\": \"FAILED\"},",
            "      {\"build\": 5, \"result\": \"SKIPPED\"},",
            "      {\"build\": 6, \"result\": \"PASSED\"},",
            "      {\"build\": 7, \"result\": \"PASSED\"},",
            "      {\"build\": 8, \"result\": \"FAILED\"},",
            "      {\"build\": 9, \"result\": \"PASSED\"},",
            "      {\"build\": 10, \"result\": \"PASSED\"},",
            "      {\"build\": 11, \"result\": \"SKIPPED\"},",
            "      {\"build\": 12, \"result\": \"PASSED\"},",
            "      {\"build\": 13, \"result\": \"PASSED\"},",
            "      {\"build\": 14, \"result\": \"FAILED\"},",
            "      {\"build\": 15, \"result\": \"PASSED\"},",
            "      {\"build\": 16, \"result\": \"SKIPPED\"}",
            "    ]",
            "  },",
            "  \"mark\": {\"type\": \"line\", \"point\": true},",
            "  \"encoding\": {",
            "    \"x\": {\"field\": \"build\", \"type\": \"quantitative\"},",
            "    \"y\": {\"field\": \"result\", \"type\": \"nominal\"},",
            "    \"order\": {\"field\": \"build\", \"type\": \"quantitative\"}",
            "  }",
            "}",
            "",
        ], true),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Sequence generator",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "line", "math"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"description\": \"Plots two functions using a generated sequence.\",",
            "  \"width\": 300,",
            "  \"height\": 150,",
            "  \"data\": {",
            "    \"sequence\": { \"start\": 0, \"stop\": 12.7, \"step\": 0.1, \"as\": \"x\" }",
            "  },",
            "  \"transform\": [",
            "    { \"calculate\": \"sin(datum.x)\", \"as\": \"sin(x)\" },",
            "    { \"calculate\": \"cos(datum.x)\", \"as\": \"cos(x)\" },",
            "    { \"fold\": [\"sin(x)\", \"cos(x)\"] }",
            "  ],",
            "  \"mark\": \"line\",",
            "  \"encoding\": {",
            "    \"x\": { \"type\": \"quantitative\", \"field\": \"x\" },",
            "    \"y\": { \"field\": \"value\", \"type\": \"quantitative\" },",
            "    \"color\": {",
            "      \"field\": \"key\",",
            "      \"type\": \"nominal\",",
            "      \"title\": null",
            "    }",
            "  }",
            "}",
            "",
        ], true),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Pie Chart",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "pie", "joke"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"description\": \"Reproducing http://robslink.com/SAS/democd91/pyramid_pie.htm\",",
            "  \"data\": {",
            "    \"values\": [",
            "      {\"category\": \"Sky\", \"value\": 75, \"order\": 3},",
            "      {\"category\": \"Shady side of a pyramid\", \"value\": 10, \"order\": 1},",
            "      {\"category\": \"Sunny side of a pyramid\", \"value\": 15, \"order\": 2}",
            "    ]",
            "  },",
            "  \"mark\": {\"type\": \"arc\", \"outerRadius\": 80},",
            "  \"encoding\": {",
            "    \"theta\": {",
            "      \"field\": \"value\", \"type\": \"quantitative\",",
            "      \"scale\": {\"range\": [2.35619449, 8.639379797]},",
            "      \"stack\": true",
            "    },",
            "    \"color\": {",
            "      \"field\": \"category\", \"type\": \"nominal\",",
            "      \"scale\": {",
            "        \"domain\": [\"Sky\", \"Shady side of a pyramid\", \"Sunny side of a pyramid\"],",
            "        \"range\": [\"#416D9D\", \"#674028\", \"#DEAC58\"]",
            "      },",
            "      \"legend\": {",
            "        \"orient\": \"none\",",
            "        \"title\": null,",
            "        \"columns\": 1,",
            "        \"legendX\": 200,",
            "        \"legendY\": 80",
            "      }",
            "    },",
            "    \"order\": {",
            "      \"field\": \"order\"",
            "    }",
            "  }",
            "}",
            "",
        ], true),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Donut Chart",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "pie", "donut"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"description\": \"A simple donut chart with embedded data.\",",
            "  \"data\": {",
            "    \"values\": [",
            "      {\"category\": 1, \"value\": 4},",
            "      {\"category\": 2, \"value\": 6},",
            "      {\"category\": 3, \"value\": 10},",
            "      {\"category\": 4, \"value\": 3},",
            "      {\"category\": 5, \"value\": 7},",
            "      {\"category\": 6, \"value\": 8}",
            "    ]",
            "  },",
            "  \"mark\": {\"type\": \"arc\", \"innerRadius\": 50},",
            "  \"encoding\": {",
            "    \"theta\": {\"field\": \"value\", \"type\": \"quantitative\"},",
            "    \"color\": {\"field\": \"category\", \"type\": \"nominal\"}",
            "  }",
            "}",
            "",
        ], true),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Double Donut Chart",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "pie", "donut"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"description\": \"A simple donut chart with embedded data.\",",
            "  \"data\": {",
            "    \"values\": [",
            "      {\"category\": 1, \"value\": 4, \"Other\": 2},",
            "      {\"category\": 2, \"value\": 6, \"Other\": 5},",
            "      {\"category\": 3, \"value\": 10, \"Other\": 11},",
            "      {\"category\": 4, \"value\": 3, \"Other\": 7},",
            "      {\"category\": 5, \"value\": 7, \"Other\": 1},",
            "      {\"category\": 6, \"value\": 8, \"Other\": 12}",
            "    ]",
            "  },",
            "  \"layer\": [",
            "      {",
            "        \"mark\": {\"type\": \"arc\", \"innerRadius\": 50},",
            "        \"encoding\": {",
            "            \"theta\": {\"field\": \"value\", \"type\": \"quantitative\"},",
            "            \"color\": {\"field\": \"category\", \"type\": \"nominal\"}",
            "        }",
            "      },",
            "      {",
            "        \"mark\": {\"type\": \"arc\", \"innerRadius\": 10, \"outerRadius\": 40 },",
            "        \"encoding\": {",
            "            \"theta\": {\"field\": \"Other\", \"type\": \"quantitative\"},",
            "            \"color\": {\"field\": \"category\", \"type\": \"nominal\"}",
            "        }",
            "      }",
            "  ]",
            "}",
            "",
        ], true),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Wheat and Wages Example",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "line", "bar"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"width\": 900,",
            "  \"height\": 400,",
            "  \"data\": { ",
            "    \"values\": [",
            "      {\"year\":\"1565\",\"wheat\":41,\"wages\":5},",
            "      {\"year\":\"1570\",\"wheat\":45,\"wages\":5.05},",
            "      {\"year\":\"1575\",\"wheat\":42,\"wages\":5.08},",
            "      {\"year\":\"1580\",\"wheat\":49,\"wages\":5.12},",
            "      {\"year\":\"1585\",\"wheat\":41.5,\"wages\":5.15},",
            "      {\"year\":\"1590\",\"wheat\":47,\"wages\":5.25},",
            "      {\"year\":\"1595\",\"wheat\":64,\"wages\":5.54},",
            "      {\"year\":\"1600\",\"wheat\":27,\"wages\":5.61},",
            "      {\"year\":\"1605\",\"wheat\":33,\"wages\":5.69},",
            "      {\"year\":\"1610\",\"wheat\":32,\"wages\":5.78},",
            "      {\"year\":\"1615\",\"wheat\":33,\"wages\":5.94},",
            "      {\"year\":\"1620\",\"wheat\":35,\"wages\":6.01},",
            "      {\"year\":\"1625\",\"wheat\":33,\"wages\":6.12},",
            "      {\"year\":\"1630\",\"wheat\":45,\"wages\":6.22},",
            "      {\"year\":\"1635\",\"wheat\":33,\"wages\":6.3},",
            "      {\"year\":\"1640\",\"wheat\":39,\"wages\":6.37},",
            "      {\"year\":\"1645\",\"wheat\":53,\"wages\":6.45},",
            "      {\"year\":\"1650\",\"wheat\":42,\"wages\":6.5},",
            "      {\"year\":\"1655\",\"wheat\":40.5,\"wages\":6.6},",
            "      {\"year\":\"1660\",\"wheat\":46.5,\"wages\":6.75},",
            "      {\"year\":\"1665\",\"wheat\":32,\"wages\":6.8},",
            "      {\"year\":\"1670\",\"wheat\":37,\"wages\":6.9},",
            "      {\"year\":\"1675\",\"wheat\":43,\"wages\":7},",
            "      {\"year\":\"1680\",\"wheat\":35,\"wages\":7.3},",
            "      {\"year\":\"1685\",\"wheat\":27,\"wages\":7.6},",
            "      {\"year\":\"1690\",\"wheat\":40,\"wages\":8},",
            "      {\"year\":\"1695\",\"wheat\":50,\"wages\":8.5},",
            "      {\"year\":\"1700\",\"wheat\":30,\"wages\":9},",
            "      {\"year\":\"1705\",\"wheat\":32,\"wages\":10},",
            "      {\"year\":\"1710\",\"wheat\":44,\"wages\":11},",
            "      {\"year\":\"1715\",\"wheat\":33,\"wages\":11.75},",
            "      {\"year\":\"1720\",\"wheat\":29,\"wages\":12.5},",
            "      {\"year\":\"1725\",\"wheat\":39,\"wages\":13},",
            "      {\"year\":\"1730\",\"wheat\":26,\"wages\":13.3},",
            "      {\"year\":\"1735\",\"wheat\":32,\"wages\":13.6},",
            "      {\"year\":\"1740\",\"wheat\":27,\"wages\":14},",
            "      {\"year\":\"1745\",\"wheat\":27.5,\"wages\":14.5},",
            "      {\"year\":\"1750\",\"wheat\":31,\"wages\":15},",
            "      {\"year\":\"1755\",\"wheat\":35.5,\"wages\":15.7},",
            "      {\"year\":\"1760\",\"wheat\":31,\"wages\":16.5},",
            "      {\"year\":\"1765\",\"wheat\":43,\"wages\":17.6},",
            "      {\"year\":\"1770\",\"wheat\":47,\"wages\":18.5},",
            "      {\"year\":\"1775\",\"wheat\":44,\"wages\":19.5},",
            "      {\"year\":\"1780\",\"wheat\":46,\"wages\":21},",
            "      {\"year\":\"1785\",\"wheat\":42,\"wages\":23},",
            "      {\"year\":\"1790\",\"wheat\":47.5,\"wages\":25.5},",
            "      {\"year\":\"1795\",\"wheat\":76,\"wages\":27.5},",
            "      {\"year\":\"1800\",\"wheat\":79,\"wages\":28.5},",
            "      {\"year\":\"1805\",\"wheat\":81,\"wages\":29.5},",
            "      {\"year\":\"1810\",\"wheat\":99,\"wages\":30},",
            "      {\"year\":\"1815\",\"wheat\":78},",
            "      {\"year\":\"1820\",\"wheat\":54}",
            "    ]",
            "  },",
            "  \"transform\": [{\"calculate\": \"+datum.year + 5\", \"as\": \"year_end\"}],",
            "  \"encoding\": {",
            "    \"y\": {",
            "      \"type\": \"quantitative\",",
            "      \"axis\": { \"zindex\": 1 }",
            "    },",
            "    \"x\": {",
            "      \"type\": \"quantitative\",",
            "      \"axis\": {\"tickCount\": 5, \"format\": \"d\"}",
            "    }",
            "  },",
            "  \"layer\": [",
            "    {",
            "      \"mark\": {\"type\": \"bar\", \"fill\": \"#aaa\", \"stroke\": \"#999\"},",
            "      \"encoding\": {",
            "        \"x\": {\"field\": \"year\"},",
            "        \"x2\": {\"field\": \"year_end\"},",
            "        \"y\": {\"field\": \"wheat\"}",
            "      }",
            "    },",
            "    {",
            "      \"data\": {",
            "        \"values\": [",
            "          { \"year\": \"1600\" },",
            "          { \"year\": \"1650\" },",
            "          { \"year\": \"1700\" },",
            "          { \"year\": \"1750\" },",
            "          { \"year\": \"1800\" }",
            "        ]",
            "      },",
            "      \"mark\": {",
            "        \"type\": \"rule\",",
            "        \"stroke\": \"#000\",",
            "        \"strokeWidth\": 0.6,",
            "        \"opacity\": 0.5",
            "      },",
            "      \"encoding\": {",
            "        \"x\": {\"field\": \"year\"}",
            "      }",
            "    },",
            "    {",
            "      \"mark\": {",
            "        \"type\": \"area\",",
            "        \"color\": \"#a4cedb\",",
            "        \"opacity\": 0.7",
            "      },",
            "      \"encoding\": {",
            "        \"x\": {\"field\": \"year\"},",
            "        \"y\": {\"field\": \"wages\"}",
            "      }",
            "    },",
            "    {",
            "      \"mark\": {\"type\": \"line\", \"color\": \"#000\", \"opacity\": 0.7},",
            "      \"encoding\": {",
            "        \"x\": {\"field\": \"year\"},",
            "        \"y\": {\"field\": \"wages\"}",
            "      }",
            "    },",
            "    {",
            "      \"mark\": {\"type\": \"line\", \"yOffset\": -2, \"color\": \"#EE8182\"},",
            "      \"encoding\": {",
            "        \"x\": {\"field\": \"year\"},",
            "        \"y\": {\"field\": \"wages\"}",
            "      }",
            "    },",
            "    {",
            "      \"data\": {",
            "        \"values\": [",
            "          {\"name\":\"Elizabeth\",\"start\":1565,\"end\":1603,\"index\":0},",
            "          {\"name\":\"James I\",\"start\":1603,\"end\":1625,\"index\":1},",
            "          {\"name\":\"Charles I\",\"start\":1625,\"end\":1649,\"index\":2},",
            "          {\"name\":\"Cromwell\",\"start\":1649,\"end\":1660,\"commonwealth\":true,\"index\":3},",
            "          {\"name\":\"Charles II\",\"start\":1660,\"end\":1685,\"index\":4},",
            "          {\"name\":\"James II\",\"start\":1685,\"end\":1689,\"index\":5},",
            "          {\"name\":\"W&M\",\"start\":1689,\"end\":1702,\"index\":6},",
            "          {\"name\":\"Anne\",\"start\":1702,\"end\":1714,\"index\":7},",
            "          {\"name\":\"George I\",\"start\":1714,\"end\":1727,\"index\":8},",
            "          {\"name\":\"George II\",\"start\":1727,\"end\":1760,\"index\":9},",
            "          {\"name\":\"George III\",\"start\":1760,\"end\":1820,\"index\":10},",
            "          {\"name\":\"George IV\",\"start\":1820,\"end\":1820,\"index\":11}",
            "        ]",
            "      },",
            "      \"transform\": [",
            "        { \"calculate\": \"((!datum.commonwealth && datum.index % 2) ? -1: 1) * 2 + 95\", \"as\": \"offset\" },",
            "        { \"calculate\": \"95\", \"as\": \"y\" }",
            "      ],",
            "      \"mark\": {\"type\": \"bar\", \"stroke\": \"#000\"},",
            "      \"encoding\": {",
            "        \"x\": {\"field\": \"start\"},",
            "        \"x2\": {\"field\": \"end\"},",
            "        \"y\": {\"field\": \"y\"},",
            "        \"y2\": { \"field\": \"offset\" },",
            "        \"fill\": {",
            "          \"field\": \"commonwealth\",",
            "          \"scale\": { \"range\": [\"black\", \"white\"] },",
            "          \"legend\": null",
            "        }",
            "      }",
            "    },",
            "    {",
            "      \"data\": {",
            "        \"values\": [",
            "          {\"name\":\"Elizabeth\",\"start\":1565,\"end\":1603,\"index\":0},",
            "          {\"name\":\"James I\",\"start\":1603,\"end\":1625,\"index\":1},",
            "          {\"name\":\"Charles I\",\"start\":1625,\"end\":1649,\"index\":2},",
            "          {\"name\":\"Cromwell\",\"start\":1649,\"end\":1660,\"commonwealth\":true,\"index\":3},",
            "          {\"name\":\"Charles II\",\"start\":1660,\"end\":1685,\"index\":4},",
            "          {\"name\":\"James II\",\"start\":1685,\"end\":1689,\"index\":5},",
            "          {\"name\":\"W&M\",\"start\":1689,\"end\":1702,\"index\":6},",
            "          {\"name\":\"Anne\",\"start\":1702,\"end\":1714,\"index\":7},",
            "          {\"name\":\"George I\",\"start\":1714,\"end\":1727,\"index\":8},",
            "          {\"name\":\"George II\",\"start\":1727,\"end\":1760,\"index\":9},",
            "          {\"name\":\"George III\",\"start\":1760,\"end\":1820,\"index\":10},",
            "          {\"name\":\"George IV\",\"start\":1820,\"end\":1820,\"index\":11}",
            "        ]",
            "      },",
            "      \"transform\": [",
            "        { \"calculate\": \"((!datum.commonwealth && datum.index % 2) ? -1: 1) + 95\", \"as\": \"off2\" },",
            "        { \"calculate\": \"+datum.start + (+datum.end - +datum.start)/2\", \"as\": \"x\"}",
            "      ],",
            "      \"mark\": {",
            "        \"type\": \"text\",",
            "        \"yOffset\": 16,",
            "        \"fontSize\": 9,",
            "        \"baseline\": \"bottom\",",
            "        \"fontStyle\": \"italic\"",
            "      },",
            "      \"encoding\": {",
            "        \"x\": {\"field\": \"x\"},",
            "        \"y\": {\"field\": \"off2\"},",
            "        \"text\": {\"field\": \"name\"}",
            "      }",
            "    }",
            "  ],",
            "  \"config\": {",
            "    \"axis\": {",
            "      \"title\": null,",
            "      \"gridColor\": \"white\",",
            "      \"gridOpacity\": 0.25,",
            "      \"domain\": false",
            "    },",
            "    \"view\": { \"stroke\": \"transparent\" }",
            "  }",
            "}",
        ]),
    },
    {
        diagramType: "vegalite",
        default: false,
        description: "Bullet Chart",
        title: "Vega-Lite",
        doc: "https://vega.github.io/vega-lite/docs/",
        keywords: ["chart", "dataviz", "bullet", "bar"],
        source: lines([
            "{",
            "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v5.json\",",
            "  \"data\": {",
            "    \"values\": [",
            "      {\"title\":\"Revenue\", \"subtitle\":\"US$, in thousands\", \"ranges\":[150,225,300],\"measures\":[220,270],\"markers\":[250]},",
            "      {\"title\":\"Profit\", \"subtitle\":\"%\", \"ranges\":[20,25,30],\"measures\":[21,23],\"markers\":[26]},",
            "      {\"title\":\"Order Size\", \"subtitle\":\"US$, average\", \"ranges\":[350,500,600],\"measures\":[100,320],\"markers\":[550]},",
            "      {\"title\":\"New Customers\", \"subtitle\":\"count\", \"ranges\":[1400,2000,2500],\"measures\":[1000,1650],\"markers\":[2100]},",
            "      {\"title\":\"Satisfaction\", \"subtitle\":\"out of 5\", \"ranges\":[3.5,4.25,5],\"measures\":[3.2,4.7],\"markers\":[4.4]}",
            "    ]",
            "  },",
            "  \"facet\": {",
            "    \"row\": {",
            "      \"field\": \"title\", \"type\": \"ordinal\",",
            "      \"header\": {\"labelAngle\": 0, \"title\": \"\"}",
            "    }",
            "  },",
            "  \"spacing\": 10,",
            "  \"spec\": {",
            "    \"encoding\": {",
            "      \"x\": {",
            "        \"type\": \"quantitative\",",
            "        \"scale\": {\"nice\": false},",
            "        \"title\": null",
            "      }",
            "    },",
            "    \"layer\": [{",
            "      \"mark\": {\"type\": \"bar\", \"color\": \"#eee\"},",
            "      \"encoding\": {\"x\": {\"field\": \"ranges[2]\"}}",
            "    },{",
            "      \"mark\": {\"type\": \"bar\", \"color\": \"#ddd\"},",
            "      \"encoding\": {\"x\": {\"field\": \"ranges[1]\"}}",
            "    },{",
            "      \"mark\": {\"type\": \"bar\", \"color\": \"#ccc\"},",
            "      \"encoding\": {\"x\": {\"field\": \"ranges[0]\"}}",
            "    },{",
            "      \"mark\": {\"type\": \"bar\", \"color\": \"lightsteelblue\", \"size\": 10},",
            "      \"encoding\": {\"x\": {\"field\": \"measures[1]\"}}",
            "    },{",
            "      \"mark\": {\"type\": \"bar\", \"color\": \"steelblue\", \"size\": 10},",
            "      \"encoding\": {\"x\": {\"field\": \"measures[0]\"}}",
            "    },{",
            "      \"mark\": {\"type\": \"tick\", \"color\": \"black\"},",
            "      \"encoding\": {\"x\": {\"field\": \"markers[0]\"}}",
            "    }]",
            "  },",
            "  \"resolve\": {\"scale\": {\"x\": \"independent\"}},",
            "  \"config\": {\"tick\": {\"thickness\": 2}}",
            "}",
        ]),
    },
]);

export default vegalite;
