import { defineExamples, lines } from '../define';

const wavedrom = defineExamples([
    {
        diagramType: "wavedrom",
        default: true,
        description: "Default",
        title: "WaveDrom",
        doc: "https://wavedrom.com/tutorial.html",
        language: "json",
        keywords: ["diagram", "wave", "timing", "electric", "signal"],
        source: lines([
            "{ signal: [",
            "  { name: \"clk\",         wave: \"p.....|...\" },",
            "  { name: \"Data\",        wave: \"x.345x|=.x\", data: [\"head\", \"body\", \"tail\", \"data\"] },",
            "  { name: \"Request\",     wave: \"0.1..0|1.0\" },",
            "  {},",
            "  { name: \"Acknowledge\", wave: \"1.....|01.\" }",
            "]}",
        ]),
    },
    {
        diagramType: "wavedrom",
        default: false,
        description: "Basic",
        title: "WaveDrom",
        doc: "https://wavedrom.com/tutorial.html",
        keywords: ["diagram", "wave", "timing", "electric", "signal"],
        source: lines([
            "{ signal: [",
            "  { name: \"Alfa\", wave: \"01.zx=ud.\" },",
            "  { name: \"Col\", wave: \"23.456789\" },",
            "  { name: \"pclk\", wave: 'p.......' },",
            "  { name: \"Pclk\", wave: 'P.......' },",
            "  { name: \"nclk\", wave: 'n.......' },",
            "  { name: \"Nclk\", wave: 'N.......' },",
            "  {},",
            "  { name: 'clk0', wave: 'phnlPHNL' },",
            "  { name: 'clk1', wave: 'xhlhLHl.' },",
            "  { name: 'clk2', wave: 'hpHplnLn' },",
            "  { name: 'clk3', wave: 'nhNhplPl' },",
            "  { name: 'clk4', wave: 'xlh.L.Hx' },",
            "]}",
        ]),
    },
    {
        diagramType: "wavedrom",
        default: false,
        description: "Spline arrows",
        title: "WaveDrom",
        doc: "https://wavedrom.com/tutorial.html",
        keywords: ["diagram", "wave", "timing", "electric", "signal"],
        source: lines([
            "{ signal: [",
            "  { name: 'A', wave: '01........0....',  node: '.a........j' },",
            "  { name: 'B', wave: '0.1.......0.1..',  node: '..b.......i' },",
            "  { name: 'C', wave: '0..1....0...1..',  node: '...c....h..' },",
            "  { name: 'D', wave: '0...1..0.....1.',  node: '....d..g...' },",
            "  { name: 'E', wave: '0....10.......1',  node: '.....ef....' }",
            "  ],",
            "  edge: [",
            "    'a~b t1', 'c-~a t2', 'c-~>d time 3', 'd~-e',",
            "    'e~>f', 'f->g', 'g-~>h', 'h~>i some text', 'h~->j'",
            "  ]",
            "}",
        ]),
    },
    {
        diagramType: "wavedrom",
        default: false,
        description: "Sharp line arrows",
        title: "WaveDrom",
        doc: "https://wavedrom.com/tutorial.html",
        keywords: ["diagram", "wave", "timing", "electric", "signal"],
        source: lines([
            "{ signal: [",
            "  { name: 'A', wave: '01..0..',  node: '.a..e..' },",
            "  { name: 'B', wave: '0.1..0.',  node: '..b..d.', phase:0.5 },",
            "  { name: 'C', wave: '0..1..0',  node: '...c..f' },",
            "  {                              node: '...g..h' }",
            "  ],",
            "  edge: [",
            "    'b-|a t1', 'a-|c t2', 'b-|-c t3', 'c-|->e t4', 'e-|>f more text',",
            "    'e|->d t6', 'c-g', 'f-h', 'g<->h 3 ms'",
            "  ]",
            "}",
        ]),
    },
]);

export default wavedrom;
