import { defineExamples, lines } from '../define';

const wireviz = defineExamples([
    {
        diagramType: "wireviz",
        default: true,
        description: "Default",
        title: "WireViz",
        doc: "https://github.com/formatc1702/WireViz/blob/master/tutorial/readme.md#02---adding-parameters-and-colors",
        keywords: ["wires", "cables", "wireviz", "hardware", "wiring", "connector pinouts", "yaml", "60757"],
        source: lines([
            "connectors:",
            "  X1:",
            "    type: D-Sub",
            "    subtype: female",
            "    pinlabels: [DCD, RX, TX, DTR, GND, DSR, RTS, CTS, RI]",
            "  X2:",
            "    type: Molex KK 254",
            "    subtype: female",
            "    pinlabels: [GND, RX, TX]",
            "",
            "cables:",
            "  W1:",
            "    gauge: 0.25 mm2",
            "    length: 0.2",
            "    color_code: DIN",
            "    wirecount: 3",
            "    shield: true",
            "",
            "connections:",
            "  -",
            "    - X1: [5,2,3]",
            "    - W1: [1,2,3]",
            "    - X2: [1,3,2]",
            "  -",
            "    - X1: 5",
            "    - W1: s",
        ]),
    },
    {
        diagramType: "wireviz",
        default: false,
        description: "Pinouts, shielding, templates",
        title: "WireViz",
        doc: "https://github.com/formatc1702/WireViz/blob/master/tutorial/readme.md#03---pinouts-shielding-templates-i",
        keywords: ["wires", "cables", "wireviz", "hardware", "wiring", "connector pinouts", "yaml", "60757", "pinouts", "shielding", "templates"],
        source: lines([
            "connectors:",
            "  X1: &template1 # define a template for later use",
            "    pinlabels: [GND, VCC, RX, TX] # pincount implicit in pinout",
            "    type: Molex KK 254",
            "    subtype: female",
            "  X2:",
            "    <<: *template1 # reuse template",
            "",
            "cables:",
            "  W1:",
            "    wirecount: 4",
            "    length: 1",
            "    gauge: 0.25 mm2",
            "    show_equiv: true",
            "    color_code: DIN # auto-assign colors based on DIN 47100",
            "    shield: true # add cable shielding",
            "",
            "connections:",
            "  -",
            "    - X1: [1-4]",
            "    - W1: [1-4]",
            "    - X2: [1,2,4,3]",
            "  - # connect the shielding to a pin",
            "    - X1: 1",
            "    - W1: s",
        ]),
    },
    {
        diagramType: "wireviz",
        default: false,
        description: "Templates (II), notes, American standards, daisy chaining (I)",
        title: "WireViz",
        doc: "https://github.com/formatc1702/WireViz/blob/master/tutorial/readme.md#04---templates-ii-notes-american-standards-daisy-chaining-i",
        keywords: ["wires", "cables", "wireviz", "hardware", "wiring", "connector pinouts", "yaml", "60757", "daisy", "chaining"],
        source: lines([
            "connectors:",
            "  X1: &template_con",
            "    pinlabels: [GND, VCC, SCL, SDA]",
            "    type: Molex KK 254",
            "    subtype: male",
            "    notes: to microcontroller # add notes",
            "  X2:",
            "    <<: *template_con # use template",
            "    subtype: female   # but override certain parameters",
            "    notes: to accelerometer",
            "  X3:",
            "    <<: *template_con",
            "    subtype: female",
            "    notes: to temperature sensor",
            "",
            "cables:",
            "  W1: &template_cbl",
            "    wirecount: 4",
            "    length: 0.3",
            "    gauge: 24 AWG # specify gauge in AWG directly",
            "    color_code: IEC # IEC 62 colors also supported",
            "    notes: This cable is a bit longer",
            "  W2:",
            "    <<: *template_cbl",
            "    length: 0.1",
            "    notes: This cable is a bit shorter",
            "",
            "connections:",
            "  -",
            "    - X1: [1-4]",
            "    - W1: [1-4]",
            "    - X2: [1-4]",
            "  - # daisy chain connectors (in line)",
            "    - X2: [1-4]",
            "    - W2: [1-4]",
            "    - X3: [1-4]",
        ]),
    },
    {
        diagramType: "wireviz",
        default: false,
        description: "Ferrules, wire bundles, custom wire colors",
        title: "WireViz",
        doc: "https://github.com/formatc1702/WireViz/blob/master/tutorial/readme.md#05---ferrules-wire-bundles-custom-wire-colors",
        keywords: ["wires", "cables", "wireviz", "hardware", "wiring", "connector pinouts", "yaml", "60757", "ferrules", "bundles", "custom", "colors"],
        source: lines([
            "connectors:",
            "  X1:",
            "    pinlabels: [+12V, GND, GND, +5V]",
            "    type: Molex 8981",
            "    subtype: female",
            "  F1:",
            "    style: simple",
            "    autogenerate: true",
            "    type: Crimp ferrule",
            "    subtype: 0.5 mm²",
            "    color: OG # optional color",
            "",
            "cables:",
            "  W1:",
            "    category: bundle # bundle",
            "    length: 0.3",
            "    gauge: 0.5 mm2",
            "    colors: [YE, BK, BK, RD] # custom colors, wirecount is implicit",
            "",
            "connections:",
            "  -",
            "    - F1 # a new ferrule is auto-generated for each of the four wires",
            "    - W1: [1-4]",
            "    - X1: [1-4]",
        ]),
    },
    {
        diagramType: "wireviz",
        default: false,
        description: "Custom ferrules",
        title: "WireViz",
        doc: "https://github.com/formatc1702/WireViz/blob/master/tutorial/readme.md#06---custom-ferrules",
        keywords: ["wires", "cables", "wireviz", "hardware", "wiring", "connector pinouts", "yaml", "60757", "custom", "ferrules"],
        source: lines([
            "connectors:",
            "  X1:",
            "    pinlabels: [+12V, GND, GND, +5V]",
            "    type: Molex 8981",
            "    subtype: female",
            "  F_10: # this is a unique ferrule",
            "    style: simple",
            "    show_name: false # non-autogenerated connectors show their name by default; override",
            "    type: Crimp ferrule",
            "    subtype: 1.0 mm²",
            "    color: YE # optional color",
            "  F_05: # this is a ferrule that will be auto-generated on demand",
            "    style: simple",
            "    autogenerate: true",
            "    type: Crimp ferrule",
            "    subtype: 0.5 mm²",
            "    color: OG",
            "",
            "cables:",
            "  W1:",
            "    category: bundle # bundle",
            "    length: 0.3",
            "    gauge: 0.5 mm2",
            "    colors: [YE, BK, BK, RD] # custom colors, wirecount is implicit",
            "",
            "connections:",
            "    -",
            "      - [F_05, F_10, F_10, F_05]",
            "      - W1: [1-4]",
            "      - X1: [1-4]",
        ]),
    },
    {
        diagramType: "wireviz",
        default: false,
        description: "Daisy chaining (II)",
        title: "WireViz",
        doc: "https://github.com/formatc1702/WireViz/blob/master/tutorial/readme.md#07---daisy-chaining-ii",
        keywords: ["wires", "cables", "wireviz", "hardware", "wiring", "connector pinouts", "yaml", "60757", "daisy", "chaining"],
        source: lines([
            "connectors:",
            "  X1: &template_con",
            "    type: Molex KK 254",
            "    subtype: female",
            "    pinlabels: [GND, VCC, SCL, SDA]",
            "  X2:",
            "    <<: *template_con",
            "  X3:",
            "    <<: *template_con",
            "  X4:",
            "    <<: *template_con",
            "  X5:",
            "    <<: *template_con",
            "  X6:",
            "    <<: *template_con",
            "",
            "cables:",
            "  W1: &template_wire",
            "    gauge: 0.25 mm2",
            "    length: 0.2",
            "    colors: [TQ, PK, YE, VT]",
            "    category: bundle",
            "  W2:",
            "    <<: *template_wire",
            "  W3:",
            "    <<: *template_wire",
            "  W4:",
            "    <<: *template_wire",
            "  W5:",
            "    <<: *template_wire",
            "",
            "connections:",
            "  -",
            "    - X1: [1-4]",
            "    - W1: [1-4]",
            "    - X2: [1-4]",
            "  -",
            "    - X3: [1-4]",
            "    - W2: [1-4]",
            "    - X2: [1-4]",
            "  -",
            "    - X3: [1-4]",
            "    - W3: [1-4]",
            "    - X4: [1-4]",
            "  -",
            "    - X5: [1-4]",
            "    - W4: [1-4]",
            "    - X4: [1-4]",
            "  -",
            "    - X5: [1-4]",
            "    - W5: [1-4]",
            "    - X6: [1-4]",
        ]),
    },
    {
        diagramType: "wireviz",
        default: false,
        description: "Part numbers and additional components",
        title: "WireViz",
        doc: "https://github.com/formatc1702/WireViz/blob/master/tutorial/readme.md#08---part-numbers-and-additional-components",
        keywords: ["wires", "cables", "wireviz", "hardware", "wiring", "connector pinouts", "yaml", "60757", "part numbers", "additional components"],
        source: lines([
            "options:",
            "  mini_bom_mode: false",
            "",
            "connectors:",
            "  X1: &template1 # define a template for later use",
            "    type: Molex KK 254",
            "    pincount: 4",
            "    subtype: female",
            "    manufacturer: '<a href=\"https://www.molex.com/\">Molex</a>' # set manufacter name",
            "    mpn: '<a href=\"https://www.molex.com/molex/products/part-detail/crimp_housings/0022013047\">22013047</a>' # set manufacturer part number",
            "    supplier: Digimouse",
            "    spn: 1234",
            "    # add a list of additional components to a part (shown in graph)",
            "    additional_components:",
            "      -",
            "        type: Crimp # short identifier used in graph",
            "        subtype: Molex KK 254, 22-30 AWG # extra information added to type in bom",
            "        qty_multiplier: populated # multipier for quantity (number of populated pins)",
            "        manufacturer: Molex # set manufacter name",
            "        mpn: 08500030 # set manufacturer part number",
            "      -",
            "        type: Test",
            "        qty: 1",
            "        pn: ABC",
            "        manufacturer: Molex",
            "        mpn: 45454",
            "        supplier: Mousikey",
            "        spn: 9999",
            "  X2:",
            "    <<: *template1 # reuse template",
            "    pn: CON4 # set an internal part number for just this connector",
            "  X3:",
            "    <<: *template1 # reuse template",
            "",
            "cables:",
            "  W1:",
            "    wirecount: 4",
            "    length: 1",
            "    gauge: 0.25 mm2",
            "    color_code: IEC",
            "    manufacturer: CablesCo",
            "    mpn: ABC123",
            "    supplier: Cables R Us",
            "    spn: 999-888-777",
            "    pn: CAB1",
            "  W2:",
            "    category: bundle",
            "    length: 1",
            "    gauge: 0.25 mm2",
            "    colors: [YE, BK, BK, RD]",
            "    manufacturer: [WiresCo,WiresCo,WiresCo,WiresCo] # set a manufacter per wire",
            "    mpn: [W1-YE,W1-BK,W1-BK,W1-RD]",
            "    supplier: [WireShack,WireShack,WireShack,WireShack]",
            "    spn: [1001,1002,1002,1009]",
            "    pn: [WIRE1,WIRE2,WIRE2,WIRE3]",
            "    # add a list of additional components to a part (shown in graph)",
            "    additional_components:",
            "      -",
            "        type: Sleve # short identifier used in graph",
            "        subtype: Braided nylon, black, 3mm # extra information added to type in bom",
            "        qty_multiplier: length # multipier for quantity (length of cable)",
            "        unit: m",
            "        pn: SLV-1",
            "",
            "",
            "connections:",
            "  -",
            "    - X1: [1-4]",
            "    - W1: [1-4]",
            "    - X2: [1-4]",
            "  -",
            "    - X1: [1-4]",
            "    - W2: [1-4]",
            "    - X3: [1-4]",
            "",
            "additional_bom_items:",
            "  - # define an additional item to add to the bill of materials (does not appear in graph)",
            "    description: Label, pinout information",
            "    qty: 2",
            "    designators:",
            "      - X2",
            "      - X3",
            "    manufacturer: '<a href=\"https://www.bradyid.com\">Brady</a>'",
            "    mpn: '<a href=\"https://www.bradyid.com/wire-cable-labels/bmp71-bmp61-m611-tls-2200-nylon-cloth-wire-general-id-labels-cps-2958789\">B-499</a>'",
            "    pn: Label-ID-1",
        ]),
    },
]);

export default wireviz;
