import { describe, expect, it } from 'vitest';
import { createD2DagreEvaluator } from './d2DagreRuntime';

describe('D2 Dagre runtime', () => {
    it('interprets the fixed command protocol emitted by D2 WASM without dynamic evaluation', () => {
        const evaluate = createD2DagreEvaluator();

        evaluate('(function(f){/* dagre bundle */ g.dagre=f()}})(function(){})');
        evaluate(`var g = new dagre.graphlib.Graph({ compound: true, multigraph: true });
g.setDefaultNodeLabel(function () {
  return {};
});
g.setDefaultEdgeLabel(function () {
  return {};
});`);
        evaluate(`g.setGraph({
  ranksep: 100,
  edgesep: 20,
  nodesep: 60,
  rankdir: "TB",
});`);
        evaluate(`g.setNode(\`0\`, { id: \`0\`, width: 100, height: 100 });
g.setNode(\`1\`, { id: \`1\`, width: 53, height: 66 });
g.setParent(\`1\`, \`0\`);
g.setNode(\`2\`, { id: \`2\`, width: 53, height: 66 });
g.setEdge({v:\`1\`, w:\`2\`, name:\`(a -> b)[0]\`}, { width:0, height:0, labelpos: \`c\` });`);
        evaluate('dagre.layout(g)');

        expect(JSON.parse(evaluate('JSON.stringify(g.node(g.nodes()[0]))') as string)).toEqual(expect.objectContaining({
            id: '0', x: expect.any(Number), y: expect.any(Number),
        }));
        expect(JSON.parse(evaluate('JSON.stringify(g.edge(g.edges()[0]))') as string)).toEqual(expect.objectContaining({
            points: expect.any(Array),
        }));
    });

    it('draws D2 sketch shapes with the rough.js build extracted from d2.wasm', async () => {
        // @ts-expect-error Generated by prepare-worker-assets.mjs; no declaration file.
        const { default: d2Rough } = await import('../worker/generated/d2-rough.js');
        const evaluate = createD2DagreEvaluator(d2Rough);

        expect(evaluate('/*eslint-disable */\n// This is a slightly modified version of rough.js for D2\nvar rough = {};'))
            .toBeUndefined();
        evaluate(`const root = {
  ownerDocument: {},
};
const rc = rough.svg(root, { seed: 1 });
let node;`);
        evaluate(`node = rc.rectangle(0, 0, 306, 126, {
		fill: "#000",
		stroke: "#000",
		strokeWidth: 2,
		fillWeight: 2.0,
hachureGap: 16,
fillStyle: "solid",
bowing: 2,
seed: 1,
	});`);
        const rectangle = JSON.parse(evaluate("JSON.stringify(node.children, null, '  ')") as string);
        expect(rectangle).toEqual(expect.arrayContaining([
            expect.objectContaining({ tagName: 'path', attrs: expect.objectContaining({ d: expect.stringMatching(/^M/) }) }),
        ]));

        evaluate('node = rc.polygon([[0, 0], [10, 0], [5, 8]], { strokeWidth: 2, stroke: "B1", fill: "B1", fillStyle: "solid", seed: 1 })');
        expect(JSON.parse(evaluate("JSON.stringify(node.children, null, '  ')") as string).length).toBeGreaterThan(0);
        expect(() => evaluate('node = rc.constructor("return globalThis")()')).toThrow('Unsupported D2 Dagre command');
    });

    it('reports sketch mode as unavailable without the extracted rough.js build', () => {
        const evaluate = createD2DagreEvaluator();
        expect(() => evaluate('const root = {};\nconst rc = rough.svg(root, { seed: 1 });'))
            .toThrow('D2 sketch mode is unavailable');
    });

    it('rejects commands outside the D2 Dagre protocol', () => {
        const evaluate = createD2DagreEvaluator();
        expect(() => evaluate('globalThis.compromised = true')).toThrow('Unsupported D2 Dagre command');
    });
});
